### ISSUE TITLE
Identify best code hook for complexity estimation

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#116]
Currently, the `initialize` method of our `ComputationalRoutine` uses dry-runs of the provided `computeFunction` for HDF5 dataset pre-allocation. Specifically, the class attributes `self.sourceLayout`, `self.targetShapes` and `self.chunkMem` might be a good starting point to get a (lower) bound for memory consumption.

**Comment by dfsp-spirit** [comment]
@Zer0day @pantaray Is this still relevant/something you want to do, or can we close this?

**Comment by pantaray** [comment]
Hi! I don't think this is something we'll follow up on in the near future, so I think the issue can be closed.

**Comment by tensionhead** [comment]
Roger, thx for letting us know!
