### ISSUE TITLE
inducer bug - spy.selectdata-

### ISSUE THREAD

**Issue by peterseneva** [esi-neuroscience/syncopy#130]
Thank you for taking the time to report an issue! We know that writing detailed error reports takes effort, and we appreciate you taking the time.

**Describe the bug**
![image](https://user-images.githubusercontent.com/91311841/134635418-52a90ed9-3c5c-4d1e-bee7-430968806ba8.png)

![image](https://user-images.githubusercontent.com/91311841/134636327-0058f737-ca94-49a9-8bde-26afa330067c.png)

![image](https://user-images.githubusercontent.com/91311841/134635710-dad8e96a-84fb-45ac-a96a-25bf5751e13b.png)

**To Reproduce**
1. Load/Import dataset 
2. select only certain amount of channel with the fuction spy.selectdata(data, channel = [x,y,z])
3. Error message/erroneous result. 

**Thank you again for your time!**

**Comment by pantaray** [comment]
Temporarily repaired w/hotfix in production: `ComputationalRoutine` does not compute stacking dimension correctly, cf.  `conda/envs/esi-2021a/lib/python3.8/site-packages/syncopy/shared/computational_routine.py`
```
        chunkShape = tuple(chk_arr.max(axis=0))
        if chunkShape != trials[0].shape and not self.keeptrials:
            err = "Averaging trials of unequal lengths in output currently not supported!"
            raise NotImplementedError(err)
...
        # Determine trial-stacking dimension                                                                                                                                                                       
        if "time" in data.dimord:
            trlDim = data.dimord.index("time")
            totalSize = sum(cShape[trlDim] for cShape in chk_list)
            outputShape = list(chunkShape)
            outputShape[trlDim] = totalSize
        self.outputShape = tuple(outputShape)
        # self.outputShape = (chk_arr[:, 0].sum(),) + chunkShape[1:] # This is wrong!                                                                                                                                                 
        self.cfg["chunkShape"] = chunkShape
        self.dtype = np.dtype(dtp_list[0])
```
This needs to be modified for objects lacking a `"time"` dimension too!
