### ISSUE TITLE
Layout new data class for connectivity data

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#143]
Implement first draft of `CrossSpectralData` class. Current concept: designed as composite class with a "regular" `SpectralData` class as backing object.

**Comment by tensionhead** [comment]
We now settled on the new `CrossSpectralData` class with default `dimord = ['time', 'freq', 'channel_i', channel_j']` with commit e3fd0935825f387b1ed64e598fb566b89bd8e86f
