### ISSUE TITLE
CrossSpectralData Tests

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#144]
Write tests for the new `CrossSpectralData` class (specifically save/load functionality).

**Comment by tensionhead** [comment]
Backend tests are up and running!

**Comment by pantaray** [comment]
Include `CrossSpectralData` in `classes` of `test_basedata.py`: https://github.com/esi-neuroscience/syncopy/blob/c4ebe1684da146e4ce254f8a8d4a78da39d23fe2/syncopy/tests/test_basedata.py#L170
