### ISSUE TITLE
AnalogData - Synthetic Data support

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#147]
In use cases like tutorials or explorative analysis, it's very useful to create/play with synthetic data. As our frontends expect SyNCoPy data classes, it would be very useful to allow for *on-the-fly* creation of synthetic datasets like:

```python
import numpy as np
from syncopy.datatype import AnalogData

nSamples = 1000
nChannels = 50
my_noise = np.random.randn(nSamples, nChannels)

trl_dat = [my_big_noise, 5 * my_big_noise + 10, np.random.randn(nSamples, nChannels)]
# now trl_dat is an iterable, where each element constitutes a trial
# for synthetic data we can assume that the individual trials will all have equal lengths/nChannel
# So there are 3 trials in total, which should get a sampleinfo like [[0, 999], [1000, 1999], [2000, 2999]]
test_data = AnalogData(trl_dat)
```
edited for more clarity, @pantaray would that be enough to specify an easy-to-use interface?!

**Comment by pantaray** [comment]
Yest, thank you! Now I get the intent - good idea and nice interface! Will incorporate that ASAP.
