### ISSUE TITLE
Remove HDF5-dataset-indexing workaround in ComputationalRoutine

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#15]
A bug preventing empty indexing arrays to be processed correctly by `h5py` triggered exceptions in `ComputationalRoutine` (specifically in `compute_sequential` but also in the `unwrap_io` decorator fueled by `compute_parallel`). A temporary workaround has been built in - as soon as `h5py` version 2.10 is available via `conda` this workaround should be removed. 

As of this writing, no pre-built wheels of version 2.10 are available for linux in `pip`, thus requiring manual compilation of the 2.10-sources against an existing `libhdf5.so` + headers - which is really not worth the trouble just for directly handling empty indexing arrays (which themselves are most likely the product of erroneous data selections anyway...)

**Comment by tensionhead** [comment]
With h5py >3 this issue got resolved
