### ISSUE TITLE
Provide an easy way to clear user-defined in-place selections

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#159]
Right now, users can set in-place selections by setting `inplace=True` in `selectdata`, however, existing selections can only be cleared by manually invoking `data._selection = None`. This is not only undocumented and unintuitive, it's also bad practice to encourage mashing around with `_` attributes. 
@tensionhead How about including an additional keyword `clear` in `selectdata` to remove any existing in-place selections?

**Comment by tensionhead** [comment]
A kw like `clear` sounds about right to me!

**Comment by pantaray** [comment]
(y) Okay, will go ahead and incorporate it
