### ISSUE TITLE
Explore alternative Wilson implementation

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#172]
Test whether `np.linalg.solve` and `np.linalg.lstsq` can replace MATLAB's `\` and `/` (`mldivide` and `mrdivide`, respectively) in the implementation of Wilson's spectral factorization algorithm so that we can retire `np.inv`.

**Comment by tensionhead** [comment]
So the replacement with least-squares works, however at least for the standard test-case (Dhamala 2008 coupled AR(2)) the only thing which changes is the run-time, it goes up :grin:
