### ISSUE TITLE
Make trial access more consistent

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#174]
Most meta-functions require access to a list of trial indices. Currently, this is achieved via ad-hoc `list(range(len(data.trials)))` constructs. To make things easier (and more consistent) introduce a `triallist` attribute, such that `data.triallist = [0, 1, ..., nTrials]` and analogously `data.selection.triallist = [0, 3, 5, 7]`, for instance.

**Comment by tensionhead** [comment]
Since quite some time we have `data.selection.trial_ids` and `data.selection.trials` (now analogue to `data.trials`) which offer the desired interface. There is no direct `data.trial_ids`, which so far was no big deal so I am closing this.
