### ISSUE TITLE
toi selection

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#179]
The `toi` key of a selection dictionary expects a sequence like object of time-points. If the delta t is smaller than the one in the data, nothing bad happens. But if delta t is larger `samplerate` gets adjusted, so this is a way of getting subsampling in syncopy. However, standard vectors like `np.arange(-.0.4, 2, 0.5)` still might, due to floating point precision issues, trigger a `non-equidistancy` behavior, so in this case subsampling is effectively broken as the samplerate doesn't get adjusted. Not sure how to address this, but subsampling should be supported in a clearer interface imho. This whole `toi` as vector is something I would rather get rid off, as it's behavior is erratic/not transparent at all to the user.

**Comment by pantaray** [comment]
As discussed, subsampling via `toi` is probably a bad idea anyway which should be explicitly mentioned in the documentation. However, the erroneous `non-equidistancy` message due to round-off errors could be fixed by adjusting `_get_time` in `ContinuousData`:
```python
        elif toi is not None:
            for trlno in trials:
                _, selTime = best_match(self.time[trlno], toi)
                selTime = selTime.tolist()
                if len(selTime) > 1:
                    timeSteps = np.diff(selTime)
                    if timeSteps.min() == timeSteps.max() == 1:
                        selTime = slice(selTime[0], selTime[-1] + 1, 1)
                timing.append(selTime)
```
This should be made more robust by using something like:
```python
        elif toi is not None:
            for trlno in trials:
                _, selTime = best_match(self.time[trlno], toi)
                selTime = selTime.tolist()
                if len(selTime) > 1:
                    timeSteps = np.diff(selTime)
                    if np.allclose(timeSteps, [timeSteps[0]] * timeSteps.size):
                        selTime = slice(selTime[0], selTime[-1] + 1, 1)
                timing.append(selTime)
```

**Comment by tensionhead** [comment]
With the latest changes towards `latency` in #384 this issue obsolete.
