### ISSUE TITLE
toilim select Keyword - out of bounds Errors

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#184]
When running sth. like

```python
connectivity(data, select={"toilim" : [2,3]})
```
but the trials actually all end at say [0,1], an unspecific/wrong `SPYValueError` is thrown: 
```bash
SPYValueError: Invalid value of `select`: 'non-equidistant set of time points'; expected equidistant time points (toi) or time slice (toilim)
```
for 
```python
connectivity(data, select={"toilim" : [0,3]})
```
we have a shape mismatch
```bash
SPYValueError: Invalid value of `freq`: 'shape = (76,)'; expected array of shape (24,)
```
whereas in the both lims out of bounds scenario for
```python
freqanalysis(data, select={"toilim" : [2,3]})
```
 we get a
 ```bash
 IndexError: list index out of range
```
For `freqanalysis(data, select={"toilim" : [0,3]})` a results get computed.

**Comment by tensionhead** [comment]
Was that addressed in one of the numerous recent fixes @pantaray ?

**Comment by pantaray** [comment]
Most of it, yes. The `connectivity`-related problems were caused by fragile use of data-selections in the meta-function (fixed by your recent top-level import rewrite, I believe).

**Comment by tensionhead** [comment]
Ok then I close this!
