### ISSUE TITLE
Improve Granger interface

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#194]
After numerical explorations of the CSD regularity and our nice discussion with Ding we should:
- check for nChan / nTrial ratio << 1 
- tighten the demeaning, which has to be done again after tapering to get rid of the *noses* at 0Hz

**Comment by schoffelen** [comment]
i hope it's OK to chime in here: can the poor souls who still use matlab for the spectral factorization also learn from the discussion with Mingzhou? Is this issue anyhow related to what we called 'zigzag' in the past? Just eager to learn...

**Comment by tensionhead** [comment]
Of course, the more the merrier! I personally did not experience this zig-zagging so far, but I might have some ideas.. do you have example data to provoke this behavior? We can also take this discussion somewhere else (gitter?) if you prefer..

**Comment by schoffelen** [comment]
Hmm, I need to dig in my e-mail history for this. Some of it is documented here: http://bugzilla.fieldtriptoolbox.org/show_bug.cgi?id=2342 but for some unknown reason Martin Vinck (who provided a lot of useful insights) was reluctant to document the stuff publicly, so most of the details are probably somewhere in my mail-history. 

Long story short seems to be that the factorization might become unstable when there's strong'ish collinearity in the underlying time series (and probably more severe stability issues when there are large amounts of channels in the csd matrix). Your current issue just reminded me of the 2013 issue, but I am not sure whether these relate to the same thing.

**Comment by tensionhead** [comment]
So my gut feeling is that this is strongly related to (almost) singular cross-spectral densities, wich I assume is exactly what happens in the case of collinearity. From my recent experiences it's easy to get such cases in general, especially if you input a lot (say >10 channels). I also saw that fix and wondered what it's for!

**Comment by schoffelen** [comment]
There you have it :). Typically, I don't do large Nchan factorizations due to the non-stability in general (and also because I usually use MEG/EEG data which has a lot of common 0-lag ('collinear') rubbish in the signals anyhow).
