### ISSUE TITLE
Arithmetic operations on complex SpectralData

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#199]
When trying to multiply a `float` to a `complex64` type SpectralData object

```python
res = spy.freqanalysis(data)
res * 2.2
```
a `SPYTyperError` is thrown:
```python
SPYTypeError: Wrong type of `operand`: expected scalar of same mathematical type (real/complex) found float
```
Even an `int` should also of course work here in this case!

**Comment by pantaray** [comment]
Ha, that seems a little overly cautious ;) The intention of the underlying query in the code is to avoid that a complex number is "applied to" (i.e., added/subtracted/multiplied/divided) a real-valued data-set. The above example is of course obviously a bug in the query, however, I'm asking myself: do we actually want to gate-keep this at all? Maybe there are edge-cases, where I want to "convert" my data by multiplying by `1 + 0j`? Maybe we should remove this type-check completely? What do you think @tensionhead ?

**Comment by tensionhead** [comment]
Well, as long as one operand is a simple scalar (be it float, int or complex), I don't see any other checks being necessary!
