### ISSUE TITLE
Implement PPC

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#201]
pair-wise phase consistency

**Comment by dfsp-spirit** [comment]
This could be done by:

* in the frontend, construct loop over n*(n-1)/2 combinations
* for each combination, run cF which gets the data for the 2nd trial as index information into the HDF5 file
* accumulate results

**Comment by dfsp-spirit** [comment]
Pair-wise phase consistency has been implemented, closing as done.
