### ISSUE TITLE
The .data attribut

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#203]
For most if not all users, the _data_ are Syncopy ojects like `AnalogData` or `SpectralData`. Hence the `.data` attribut easily can lead to ambigious naming:
```python
my_data = spy.AnalogData(...)
# what is this exactly from a user perspective?
my_data.data[..]
```
As `.data` should not be directly user exposed (trial stacking along time axis is a concept our users need to know nothing about), it's not critical, but some sensible renaming to `.hdf5` or alike seems to be a good idea

**Comment by tensionhead** [comment]
As long as all experts know what this `.data` attribute is (the raw time-continuous hdf5 dataset) it's most likely fine to keep it as it is. For normal users this should never be exposed/mentioned directly.. mmh, from that reasoning maybe renaming to `._data` is also an option, or what do you think @pantaray ?

**Comment by pantaray** [comment]
I'm open to renaming the property, however, `_data` is the attribute underlying the `data` property. I actually quite like your `hdf5` suggestion. It's abstract enough to not suggest itself as a convenient way to access the underlying data, while simultaneously evocative enough to communicate to devs what's inside.

**Comment by tensionhead** [comment]
One additional complexity is the possibility that we'll have multiple hdf5 datasets attached to syncopy datatype. As long as this is not decided on, we can't do anything here imho.

**Comment by tensionhead** [comment]
We found no better solution, it's not considered part of the public API for now.. so we are leaving it as is.
