### ISSUE TITLE
SpikeData trialtime

### ISSUE THREAD

**Issue by atlaie** [esi-neuroscience/syncopy#218]
When accessing the property 'trialtime' of an SpikeData variable, it yields a a generator per spike, instead of per trial. For example:

spike_times = np.array([0, 3, 7, 12, 13, 15, 21])
channels = np.array([0, 0, 1, 0, 2, 0, 0], dtype = int)
units = np.array([0, 1, 0, 1, 1, 0, 0], dtype = int)

`a = spy.SpikeData(data = np.vstack([spike_times, channels, units]).T, trialdefinition = np.array([[0,5,2], [6,15,3]]), dimord = ['sample', 'channel', 'unit'], samplerate=5)`

When doing 

`len(a.trialtime)` we get 7 (i.e., number of spikes, not of trials).

I have coded an alternative way in which this could be done, but I don't know if it's the most efficient one! Here it is:

```
@property
def trialtime(self):
    """list(:class:`numpy.ndarray`): trigger-relative sample times in s"""
    if self.samplerate is not None and self.sampleinfo is not None:
        return [(trl[:,0] - self._t0[tk] - self.sampleinfo[tk, 0])/self.samplerate for tk, trl in enumerate(self.trials)]
```

Instead of the current definition at line 181 (discrete_data.py).

**System Profile:**
 - OS: [Windows 10]
 - Please paste the output of the following command here 
   ```python
   import syncopy as spy; spy.AnalogData().log
   ```

>>> SyNCopy v. 0.20 <<< 

Created: Fri Feb 25 10:23:06 2022 

System Profile: 
3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0] 
ACME:  0.2rc3
Dask:  2021.10.0
NumPy: 1.21.5
SciPy: 1.7.1

--- LOG ---

|=== tlaieboriaa@esi-svhpc1: Fri Feb 25 11:10:49 2022 ===|

	__init__: created AnalogData object

Thank you!

**Comment by tensionhead** [comment]
Ok I see @atlaie, thx for letting us know I will have a look into this!

**Comment by tensionhead** [comment]
So I took the solution you directly provided, with this I get:
```python
In [4]: a.trialtime
Out[4]: [array([-0.4,  0.2]), array([-0.4,  0.6,  0.8,  1.2])]
```
I guess this is correct @atlaie?

Btw you are also welcome to do a PR yourself once you have already a nice solution ;)
