### ISSUE TITLE
fooof implementation

### ISSUE THREAD

**Issue by timnaher** [esi-neuroscience/syncopy#224]
implementation of the fooof algorithm for 1/f  correction and peak detection. Python implementation here:
https://fooof-tools.github.io/fooof/

Could be cool to get estimates for aperiodic components, as well as automatic peak detection from the freq analysis 
Its also implemented in the newest field trip version.

**Comment by tensionhead** [comment]
Thx for bringing this up @timnaher, sounds indeed very useful.. I guess the core functionality is their `FOOF.fit()`algorithm which separates periodc from aperiodic components? We'll have to see if we want to add this package as a dependency or re-implement the important bits ourselfs.

**Comment by tensionhead** [comment]
For testing the proposed algorithm by the fooof authors and to generally beef up our synthetic data generation we might also want to right away include a 1/f simulator ala https://github.com/felixpatzelt/colorednoise

**Comment by dfsp-spirit** [comment]
Some links and information regarding fooof, I am just collecting this here for reference:

* the [fooof repo](https://github.com/fooof-tools/fooof) and [fooof website with docs](https://fooof-tools.github.io/fooof/), with great motivation and tutorials
* the [fieldtrip documentation for their fooof integration](https://www.fieldtriptoolbox.org/example/fooof/) shows their fooof API
* Fieldtrip uses the fooof code/implementation of the [Brainstorm package](https://neuroimage.usc.edu/brainstorm/), they have a  [fooof tutorial as well](https://neuroimage.usc.edu/brainstorm/Tutorials/Fooof)

**Comment by dfsp-spirit** [comment]
**Expected return value of fooof method in syncopy**

One of the following (which one can be requested via args):

- spectrum without 1/f (Figure 2.)
- fitted Gaussians (Figure 4.)
- fitted baseline (Figure 6.)

<img width="624" alt="foof_method" src="https://user-images.githubusercontent.com/1061893/175495889-070b98c0-5956-412d-b3d1-ecbd6f4dd268.png">

**Comment by tensionhead** [comment]
[This here](https://gist.github.com/tensionhead/ca6b13138abfaab56e506291217a4540) might help :smiley:

**Comment by dfsp-spirit** [comment]
This is on _dev_ now, closing.
