### ISSUE TITLE
Averaging operator and `.show()` interface

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#230]
For plotting and general post-processing of analyses, having the possibility to contract a certain dimension (be it `time`, `channel`, `trial` or maybe even `freq`) would be of much use. The general idea would be to have a method attached to Syncopy data objects akin to `selectdata`, however this time new (the averaged) data will also be written on disc. As an example suppose we have a `SpectralData` object `spec` with 10 channels and say 200 trials, a typical application might look like this:
```python
av_spec = spec.average(channels=['ch1', 'ch5', 'ch8'], trials='all')
```
This would create a new `SpectralData` object `av_spec` which now only has 1 trial and a singleton `channel` axis holding the trial average over the selected 3 channels, probably best called `avg` or sth similar.

Moreover, it would be useful to also allow the `.show` method to interface this averaging directly like this:
```python
out_arr = spec.show(channels=['ch1', 'ch5', 'ch8'], trials='all', average=True)
```
In case of singleton time and taper axes (`method='mtmfft'` with `taper='hann'`) this now would return a `(nFreq,)` shaped array. Alternatively, calling `.show()` without arguments on the averaged `SpectralData` object `av_spec`, should return the exact same array. 

Additionally it might be a good messaging policy, to inform the user about the size of the returned array in memory upon calling `.show(...)`.

**Comment by pantaray** [comment]
I like the interface! 

One question that comes to mind is the "correct" computation of the average. Do we compute channel averages followed by trials? Or vice versa? How about things like `spec.average(channels=['ch1', 'ch5', 'ch8'], foilim=[30, 70], trials='all')`? First frequencies, then channels then sum over trials divided by no. of trials? Not trying to sabotage the feature request, just an earnest question how to go about this.

**Comment by tensionhead** [comment]
Well, contractions along **different** axis do commute right?!

**Comment by pantaray** [comment]
Well, yes, you're right of course. Got confused (again) with time/trial axis.

**Comment by tensionhead** [comment]
What's the status here @pantaray ?

**Comment by pantaray** [comment]
Still in the "good idea" stage 😉

**Comment by tensionhead** [comment]
So as outlined in #372, the interface got implemented a bit differently: `spy.stat_operator(dim='...')`, such that multiple statistical operations have to be chained, for example like this:
```python
trl_av = spy_data.mean(dim='trials')
freq_av = trl_av.mean(dim='freq', select={'channel': [0,2])
freq_av.show()  # will return a single array with squeezed out freq axis
```
This is more transparent, as at each step a new independent Syncopy data object gets created, where selections and statistical operations are logged independently.
