### ISSUE TITLE
Streamline Tests

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#233]
Right now we have quite a ponderous testing pipeline which often bogs down testing envirnoments either due to time and/or memory requirements. Ways out of this could be:
- codecoverage analysis, maybe some things get tested more than needed
- hdf5 core driver to mitigate the cost of I/O operations for the dataype tests
- refactoring of testing routines to a more concise interface, might help deslagging

**Comment by tensionhead** [comment]
I think this is already basically done or what do you think @pantaray ? Or at least we should link your last commit which drastically improved the situation..

**Comment by pantaray** [comment]
Yup, I think this can be closed

**Comment by pantaray** [comment]
Fixed in 84bb6f047d550f64f59893da28e955db3f77685c and follow ups
