### ISSUE TITLE
Delineating Fieldtrip compatibility

### ISSUE THREAD

**Issue by joschaschmiedt** [esi-neuroscience/syncopy#235]
**Problem**
Compatibility with Fieldtrip is a core goal of the Syncopy project. However, which parts are or should be compatible to what extent is not obvious, neither for the users nor for the developers. 

The documentation contains a [section for Fieldtrip _users_](https://syncopy.readthedocs.io/en/latest/user/fieldtrip.html#translating-fieldtrip-calls-to-syncopy), but it does not give any detailed information on given functions. At the code level, for a given Syncopy function, without reading the Doc strings in detail it's not possible to predict the level of Fieldtrip compatibility. This in effect leads to trial and error for users when translating Fieldtrip calls to Syncopy.

For a _developer_ working on a new feature, it's also not clear, which parts of the new code have to be keyword and/or feature compatible with Fieldtrip, such that the decision has to be made ad-hoc. 

**Suggestion**
I propose to introduce three levels of compatibility that should be part of the documentation and code:
1. Guaranteed/**high compatibility**: 
    - a highly compatible function can be called using the exact same keyword arguments as its Fieldtrip counterpart. 
    - additional keyword arguments are allowed
    - feature parity is not guaranteed, i.e., not all features of Fieldtrip have to be implemented
    - highly compatible methods yield similar results as Fieldtrip. The (inevitable) deviation is tested and documented.
   
2. Optional/**weak compatibility**:
   - a weakly compatible function signature is very similar to its pendant in Fieldtrip, but keyword arguments may differ. The function signature is merely "inspired" by Fieldtrip.
   - numerical differences in the results are not tested by the developer

3. **No compatibility**

To achieve a predictable API for **Fieldtrip users** I suggest to create a namespace `syncopy.ft`, the **Fieldtrip Compatibility Layer (FCL)** that contains the highly and weakly compatible functions. This would allow users almost copy-paste their Fieldtrip code, and to know from simple code inspection, which Fieldtrip functions are available to them. For example,
```python
import synopy.ft as ft
cfg = ft.get_defaults(ft.freqanalysis)
cfg.method = 'mtmfft'
cfg.foilim = [1, 150]
cfg.output = 'pow'
cfg.taper = 'dpss'
cfg.tapsmofrq = 10
spec = ft.freqanalysis(cfg, data)
```

For the developers I'd suggest to limit the Fieldtrip Compatibility layer to the high-level meta-functions, which currently are 
```python
freqanalysis
preprocessing
connectivityanalysis
timelockanalysis
```
In the future I'd suggest we add at least
```
freqstatistics
timelocksatatistics
sourceanalysis
sourcestatistics
```
Focusing on these "entry point" functions that select a method to apply on the data,  gives us the freedom to change the code architecture freely. In such a scenario the FCL would be one possible API for users, and we are not bound to inherit Fieldtrip's grown, functional MATLAB architecture. 

A resulting design could then be
```mermaid
graph LR
    A[User] -->|cfg, data| B(Fieldtrip Compatibility Layer)
    B --> | *args, **kwargs | C(Method Frontend)
    A --> | *args, **kwargs | C 
    C --> D(Method Backend)
```
where the method frontend can also be a class instead of a function.

**Comment by pantaray** [comment]
I think that's a fantastic idea! I really like the `ft` namespace. Super intuitive and very elegant 👍🏻

**Comment by tensionhead** [comment]
In principle I like the idea, however we have to keep a few things in mind:

- ratio of current Syncopy users which expect exact FT behavior: 0%
- solely focussing on method arguments, whereas the differences of the language (e.g. `[]` instead of `()`, indexing starts with `0`, ...) and the **data interface** will always be quite different and the biggest obstacle in practice imho

So in that sense we have to be honest about how much of a FT experience we really can deliver with Python. That being said, I also really like the idea to abstract the FT interface away (sth similar came to my mind when I saw the *** preprocessing interface of FT) :+1:

**Comment by pantaray** [comment]
I very much disagree with this point. One of (if not the) unique selling points of SyNCoPy is its FieldTrip compatibility. The core design goal from the get-go was to enable users to to take an existing FieldTrip `cfg` and copy-paste it to a Python script with SyNCoPy working its magic behind the scenes, which ideally would look like:

1. import data from FieldTrip into Syncopy
2. perform the requested analysis using the provided `cfg`
3. use any available HPC resources without explicit user interaction
4. offer a convenient way to export computed results to FT

At best, this should even work when invoking SyNCoPy from Matlab (which as we all know comes with its own bouquet of technical difficulties). Ideally, a casual user should not even have to bother about our data-model let alone the fact that it differs from FieldTrip's. I know that's a tall ask but that was the principal idea behind SyNCoPy. We've deviated from this scenario for various good (and sometimes not so good) technical/functional reasons but I still think that this design principle is valid and very much worthwhile to strive for.

> ratio of current Syncopy users which expect exact FT behavior: 0%

Recent discussions hardly support this estimate.

> data interface will always be quite different and the biggest obstacle in practice imho

I agree that his is currently a significant obstacle but that should not be the reason to throw FT compatibility over board (quite the opposite, see above).

I know that the above stated scenario is currently definitely more dream than reality, and even if it were currently possible to use SyNCoPy as outlined above, there's a lot more to do and explore with its native Python interface. However, FT compatibility should not be an afterthought. Right now I think the most practical approach is the one outline by @joschaschmiedt  and clearly delineate incompatible/somewhat compatible/fully compatible routines.

Final note: one of the core functionalities of the FT compatibility layer is already present with the `unwrap_cfg` decorator. Currently it simply converts a `cfg` dict to keyword args, however, extending it to meta-function-specific keyword args should be straight-forward.

**Comment by tensionhead** [comment]
Erm, I guess you misunderstood my comment.. I didn't say at all that we should throw FT compatibility overboard, of course not! And the `0%` are also not an estimate but the actual (aka _"current"_) realilty of our user-base. As soon as this changes, and actual FT user experiences trickle in this topic will also get much more steam from my side, you can be sure of that :wink: 

Extending the existing wrappers (or decorators) in a way @joschaschmiedt outlined is something I totally support.

**Comment by tensionhead** [comment]
We decided to incrementally achieve closeness to FT as before, by keeping the API as close as possible.
