### ISSUE TITLE
SpikeData "waveform" property

### ISSUE THREAD

**Issue by KatharineShapcott** [esi-neuroscience/syncopy#238]
Fieldtrip's spike structure has an optional "waveform" field. It would be useful to have a similar "waveform" property in the SpikeData class so that the type of spikes (e.g. inhibitory or excitatory) can be identified. 

Quote from https://www.fieldtriptoolbox.org/tutorial/spike/

"The first dimension of spike.waveform{i} is ‘leads’. For tetrode recordings, multiple leads per electrode are available, in which case the first dimension of spike.waveform{i} would have been of size 4. 
The second dimension of waveform contains the samples. In this case one sample corresponds to 1/40000 seconds. 
The third dimension of spike.waveform{i} equals the length of spike.timestamp{i}, such that a waveform is present for every spike (‘spike’ dimension)."

We would only need this for sorted spikes though, which won't happen for a few more months.

**Comment by tensionhead** [comment]
Ah ok I see, thx @KatharineShapcott for bringing this up! @joschaschmiedt is that something you could take care of?

**Comment by KatharineShapcott** [comment]
Seems like other well used formats are also three dimensional. 

> Now we can retrieve waveforms per unit on-the-fly. The waveforms shape is (num_spikes, num_sample, num_channel):

https://spikeinterface.readthedocs.io/en/latest/modules/core/plot_4_waveform_extractor.html

In this case the extra dimension is channel which I think is definitely more general than `lead`

**Comment by tensionhead** [comment]
mmh.. what is `num_spikes` and `num_sample`?

**Comment by KatharineShapcott** [comment]
`num_spikes` is the total number of spikes, `num_sample` is the number of samples that makes up the waveform

**Comment by KatharineShapcott** [comment]
They have a seperate storage for each unit (or channel in our case) though. This might makes sense since the most common operation is to mean or median across the unit and plot the average waveform. But it will mess up all our indexing

**Comment by dfsp-spirit** [comment]
This is implemented in [PR437](https://github.com/esi-neuroscience/syncopy/pull/437).

**Comment by tensionhead** [comment]
Done with #437
