### ISSUE TITLE
Granger causality between duplicate channels is non-zero

### ISSUE THREAD

**Issue by gabbyshvartsman** [esi-neuroscience/syncopy#243]
**Describe the bug**
I was running connectivity analysis with granger causality on my own data and was doing some preliminary tests to make sure I was using the syncopy functions correctly, but when I run it on 2 duplicate channels, I am getting non-zero causality values. I would expect a zero result since there's no additional information added if the channels are the same.

**To Reproduce**
I reproduced those results using data generated by `syncopy.tests.misc.generate_artificial_data`:

```import numpy as np
import matplotlib.pyplot as plt 

from syncopy.tests.misc import generate_artificial_data
from syncopy import connectivityanalysis as ca

# Generate artificial data with 1 trial and 2 channels
artif_data = generate_artificial_data(1, 2)

# Change channel info to be 2 duplicates of the first channel
artif_data.data = np.asarray([artif_data.data[:][:, 0], artif_data.data[:][:, 0]]).T

# Run granger analysis w/ defaults from the syncopy test_connectivity tests
spectral_gc = ca(data=artif_data, method='granger', taper='dpss',
                   tapsmofrq=3, foi=np.arange(5, 75))

# Plot results (no ylim)
def plot_Granger(G, i, j):
    ax = plt.gca()
    ax.set_xlabel('frequency (Hz)')
    ax.set_ylabel(r'Granger causality(f)')
    ax.plot(G.freq, G.data[0, :, i, j], label=f'Granger {i}-{j}',
            alpha=0.7, lw=1.3)

for i in range(2):
    for j in range(2):
        plot_Granger(spectral_gc, i, j)
plt.legend()
``` 
![test_gc_nonzero](https://user-images.githubusercontent.com/35669514/159068779-c7a20a68-2519-4f4c-870f-f5ad2deef995.png)

`spectral_gc.data[:]`
```array([[[[0.    , 2.2025],
         [0.0072, 0.    ]],

        [[0.    , 2.6199],
         [0.0072, 0.    ]],

        [[0.    , 2.5049],
         [0.0072, 0.    ]],

        [[0.    , 2.7412],
         [0.0072, 0.    ]],

        [[0.    , 2.613 ],
         [0.0072, 0.    ]],

        [[0.    , 2.7652],
         [0.0072, 0.    ]],
```

**Expected behavior**
I would expect duplicate channels to have a 0 granger causality value, as they don't provide any additional information and should be performing the same calculation as the computations along the diagonal of the results.

**System Profile:**
 - OS: Ubuntu 20.04 windows subsystem for linux (on Windows 10)
 ```python
   import syncopy as spy; spy.AnalogData().log
   ```
```		>>> SyNCopy v. 0.3.dev10 <<< 

Created: Fri Mar 18 11:58:55 2022 

System Profile: 
3.8.5 (default, Aug  5 2020, 08:36:46) 
[GCC 7.3.0] 
ACME:  0.21
Dask:  2021.11.2
NumPy: 1.21.2
SciPy: 1.7.3

--- LOG ---
```

I've been stumped on this for some time now, please let me know if I'm incorrectly interpreting some of the syncopy inputs/results. Thank you!!

**Comment by tensionhead** [comment]
Ok yes, can reproduce.. thx for reporting @gabbyshvartsman! 

Oddly enough, this can't be spotted with our normal test case:

```python
import syncopy as spy
from syncopy.tests import synth_data

def granger_test(coupling = (0, 1)):                                           
                                                                                
     nTrials = 50                                                               
     nSamples = 1000                                                            
     fs = 500                                                                   
                                                                                
     AdjMat = np.zeros((2, 2))                                                  
     AdjMat[coupling] = .2                                                      
                                                                                
     trls = []                                                                  
     for _ in range(nTrials):                                                   
                          
         alphas = [.55, -.8]                                                    
         trl = synth_data.AR2_network(AdjMat, nSamples=nSamples,                
                                      alphas=alphas)                            
                                              
         trls.append(trl)                                                       
                                                                                
     ad2 = spy.AnalogData(trls, samplerate=fs)                                  
     gr = spy.connectivityanalysis(ad2, method='granger', tapsmofrq=3, polyremoval=0)                                                                         
                                                                                
     ppl.figure()                                                               
     for ch_i in [0, 1]:                                                        
         for ch_j in [0, 1]:                                                    
             ppl.plot(gr.freq, gr.show(channel_i=ch_i, channel_j=ch_j),         
                      label=rf"channel {ch_i} $\rightarrow$ channel {ch_j}")
```

Running this with `granger_test(coupling = (0, 1))` produces:
![gr_01](https://user-images.githubusercontent.com/10595420/159227645-f62e57bc-51f3-4b6b-96da-87c0bfd010e9.png)

And with `granger_test(coupling = (1, 0))`  :
![gr_10](https://user-images.githubusercontent.com/10595420/159227702-9adfbb19-91e0-4b59-a81a-543ef3fc24f2.png)

Both produce seemingly the same results, capturing the right coupling direction.. curious, will investigate!

**Comment by tensionhead** [comment]
Ok I fixed it with the latest merge into dev, I guess you were anyways working from that branch? Many many thanks for bringing this up, this was really important!

If you wanna check out the latest API improvements, have a look at:
https://syncopy.readthedocs.io/en/dev/quickstart/quickstart.html

**Comment by gabbyshvartsman** [comment]
Happy I could help! Thank you for looking into this and fixing it!

**Comment by gabbyshvartsman** [comment]
Hmm I updated to include this new fix but am still getting some values that are closer to 0 than before but not quite 0.
![test_gc_still_nonzero_zoomed_out](https://user-images.githubusercontent.com/35669514/159327326-524b4b4d-4039-4212-9eb6-774fc5063322.png)
I thought it was just one direction that was still non-zero but upon zooming in you can see that it's still both:
![test_gc_still_nonzero_zoomed_in](https://user-images.githubusercontent.com/35669514/159327365-bbf67fd0-f133-49bc-8b93-a8772f8fe827.png)
 
I switched to the dev branch and am now running this code for reference:
```import numpy as np
import matplotlib.pyplot as plt 

from syncopy.tests.misc import generate_artificial_data
from syncopy import connectivityanalysis as ca

# Generate artificial data with 2 trials and 2 channels
artif_data = generate_artificial_data(2, 2)

# Change channel info to be 2 duplicates of the first channel
artif_data.data = np.asarray([artif_data.data[:][:, 0], artif_data.data[:][:, 0]]).T

# Run granger analysis w/ defaults from the syncopy test_connectivity tests
spectral_gc = ca(data=artif_data, method='granger', tapsmofrq=3)

# Plot results (no ylim)
def plot_Granger(G, i, j):
    ax = plt.gca()
    ax.set_xlabel('frequency (Hz)')
    ax.set_ylabel(r'Granger causality(f)')
    ax.plot(G.freq, G.data[0, :, i, j], label=f'Granger {i}-{j}',
            alpha=0.7, lw=1.3)
    ax.set_ylim((0, 0.1))

for i in np.arange(2):
    for j in np.arange(2):
        plot_Granger(spectral_gc, i, j)
plt.legend()
```
Any ideas why it's not exactly 0?

**Comment by tensionhead** [comment]
Mmh, so there are at least two components here.. the DC (0-frequency) causality spikes weirdly up. A while ago some experts recommended me to de-mean again after tapering, I removed this now and I got really good results:
![gr_all](https://user-images.githubusercontent.com/10595420/159339620-5e7669e4-0c80-4563-b471-a366427913c2.png)
Note that the y-axis has 1e-6 scaling!  This is for pure white noise, so I generated the data with:
```python
trls = []                                                                                        
for _ in range(nTrials):                                                                                                         
         wn = np.random.randn(1000)
         # setting the same noise on both channels                                   
         trl = np.c_[wn, wn]                                                                            
         trls.append(trl)                                                                             
                                                                                                      
artif_data = spy.AnalogData(trls, samplerate=500)
```
Secondly, the spectral factorization of the cross-spectral densities is an iterative algorithm, meaning that it does not necessarily converge with infinite precision to the true results. Meaning that even though you are right, in principle also the off-diagonal causalities should be exactly 0, in practice that will not be the case (although 1e-6 is close enough imho).

And lastly the (rather old) artificial data routine generates harmonics, which have non-decaying cross-correlations. So this data is inherently unsuited to test the Granger algorithm. A mathematical necessity is that the cross-correlation decay to 0 *rather fast*, that's why I chose white noise now to get the best performance of the algorithm. Maybe try also the AR(2) synthetic data generation if you want something more realistic, but please avoid harmonics!

Please let me know if the latest commit also improved your results sufficiently :smiley:

**Comment by gabbyshvartsman** [comment]
Thank you for the thorough explanation!

This latest commit fixed the 0-frequency causality spike! And yeah your second point makes sense about it not necessarily converging to exactly 0.

I tried running the same test with the AR(2) synthetic data generation and it looks pretty good:
![test_gc_nonzero_ar_model](https://user-images.githubusercontent.com/35669514/159419446-fbb46e65-d95d-4660-b03d-1970946bb940.png)

I also ran it on a sample of our data and it's still returning high causality values (up to ~0.4) for duplicate channels. Not quite sure what's going on there but maybe our data has some well-defined harmonic components? Still trying to figure out what's going on...

**Comment by tensionhead** [comment]
Ok great, than from the algorithm side I think it finally works within the numerical boundaries as expected :slightly_smiling_face: We can take the discussion about your specific problems elsewhere, so I am closing this. Thanks again @gabbyshvartsman!
