### ISSUE TITLE
Consider putting together "Community Health Files"

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#25]
We might consider adding default community health files (e.g., `CONTRIBUTING.md`, `SUPPORT.md` etc.)  to the root of a public repository called `.github` that is owned by the [esi-neuroscience](https://github.com/esi-neuroscience) organization.

**Comment by tensionhead** [comment]
Having trouble understanding this, a repository that is called `.github` ? That would be global to the [esi-neuroscience](https://github.com/esi-neuroscience) organization @pantaray ?!

**Comment by pantaray** [comment]
Hi! Yes, the mechanism is explained here: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file Now, almost exactly 3 years later, I don't think it makes much sense to create organization-wide issue templates, PR checklists or contributing guidelines. At best a "global" code of conduct might make sense. However, (luckily) we never had an issue where we would have needed to point to a document stating rules of conduct. I think it would make sense to create these documents on a repository level (if needed/wanted).
