### ISSUE TITLE
Unhelpful error message if data has size 0

### ISSUE THREAD

**Issue by KatharineShapcott** [esi-neuroscience/syncopy#257]
**Describe the bug**
There should probably be a check for creating data with a dimension equal to 0. Like the error message we get if we have the wrong sized array: 
```
SPYValueError: Invalid value of `data`: '1d-array'; expected 2d-array
```
instead it's quite cryptic.

**To Reproduce**

```
spy.SpikeData(np.column_stack(([],[],[])), dimord = ['sample', 'channel', 'unit'], samplerate = 30000)

SyNCoPy encountered an error in

<stdin>, line 1 in <module>


--------------------------------------------------------------------------------
Abbreviated traceback:

/mnt/pns/home/shapcottk/python/syncopy/syncopy/datatype/discrete_data.py, line 506 in __init__
        super().__init__(data=data,
/mnt/pns/home/shapcottk/python/syncopy/syncopy/datatype/discrete_data.py, line 331 in __init__
        definetrial(self, kwargs.get("trialdefinition"))
/mnt/pns/home/shapcottk/python/syncopy/syncopy/datatype/methods/definetrial.py, line 118 in definetrial
        trl = np.array([[np.nanmin(obj.data[:,sidx]),
<__array_function__ internals>, line 5 in nanmin

/gs/home/shapcottk/.conda/envs/syncopyoe/lib/python3.8/site-packages/numpy/lib/nanfunctions.py, line 319 in nanmin
        res = np.fmin.reduce(a, axis=axis, out=out, **kwargs)

Use `import traceback; import sys; traceback.print_tb(sys.last_traceback)` for full error traceback.
ValueError: zero-size array to reduction operation fmin which has no identity

```

**Comment by dfsp-spirit** [comment]
This is related to [lines 311-318 in discrete_data.py](ValueError: zero-size array to reduction operation fmin which has no identity):

    if self.data is not None:
            if self.sampleinfo is None:
                definetrial(self, kwargs.get("trialdefinition"))

where `definetrial()` will run `np.nanmin()` on the data, resulting in the reported `ValueError: zero-size array to reduction operation fmin which has no identity`.

@pantaray I guess one way to handle this is a simple additional check for `self.data.size != 0` here before calling `definetrial()`. This would result in an empty dataset without trial definition in case of empty `self.data`, but that should be fine with us, right?

**Comment by dfsp-spirit** [comment]
Closing this as done, see linked commit.
