### ISSUE TITLE
Concatenate Syncopy data objects

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#266]
## Description
We have already one case, where users want to pool experiments (=set of trials) _before_ analyses, and then take the trial average. Which is different from averaging individual experiments, and then look at the grand average. This pooling of trials is something we don't directly support at the moment. One way to do this within the existing codebase is to mimmick our synthetic data initialization:
```python
trls = list(data1.trials) + list(data2.trials)
concat = spy.AnalogData(trls, ...)
```
This works, however does not scale to big data sets, as everything goes into RAM before concatenation.

## Solution 1 - Use Generators for initialization

Right now, a `list` of `np.array`s is needed to initialize a new `AnalogData` object, which leads to all trials being loaded into RAM. Alternatively we could initialize trial-by-trial by using generators like this:
```python
from itertools import chain
trls = chain(data1.trials, data2.trials)
concat = spy.AnalogData(trls, ...)
```
The `.trials` attribute is already a generator, only loading a single trial into memory upon request. For initializing the new `concat` data, the backing hdf5 dataset should be also filled in a trial-by-trial manner.

## Solution 2 - Dedicated `spy.concat` function

One could also imagine use cases where concatenation is requested not along trials, but maybe along channels or time and so on. For this, a new dedicated `spy.concat` function could be the general solution. This would work by operating on Syncopy data objects directly:
```python
concat = spy.concat((data1, data2), dim='channel')
```
Clever memory management would then have to implemented directly into this function.

**Comment by pantaray** [comment]
Maybe Solution 1 could be further streamlined by allowing users to input `AnalogData` objects directly in the constructor:
```python
concat = spy.AnalogData(data1, data2)
```
Then modify `_set_dataset_property_with_list` in `BaseData` akin to
```python
if isinstance(inData, AnalogData):
    trls = chain(data1.trials, data2.trials)
    ...
```

**Comment by tensionhead** [comment]
Let's address trial concatenation first by allowing generator expressions within the data class constructors, hence also addressing #285

**Comment by dfsp-spirit** [comment]
Closing as done.
