### ISSUE TITLE
mtmfft: impement detrending

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#27]
**Not really a problem per se, more like a missing feature? Please elaborate**
De-trending is currently not supported by `freqanalysis`. We should support `polyremoval` and `polyorder` keywords. Leverage `detrend` option of [stft](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.stft.html)  for this.

**Comment by tensionhead** [comment]
Addressed with d33fcc0
