### ISSUE TITLE
freqanalysis toi bug

### ISSUE THREAD

**Issue by neurochen** [esi-neuroscience/syncopy#281]
When specifying tois for spy.freqanalysis, it gives an error:  
```
res.shape = self.targetShapes[nblock]
ValueError: cannot reshape array of size 3876 into shape (50,1,51,2)
```
However, when performing the same analysis using a scalar toi, it works fine for the same time centroids defined in the array tois. It seems to be a bug for the internal calculation of time windows.

**Comment by pantaray** [comment]
Hi! Thanks for reporting this issue! Could you please provide a small example (code snippet + exemplary dataset) which triggered the error? Also, which version of Syncopy are using (`import syncopy as spy; print(spy.__version__)`? Thanks!

**Comment by neurochen** [comment]
I installed the latest version, and there is no issue with this anymore. Thanks.
