### ISSUE TITLE
Allow unequal trials np.array data initialization + generators

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#285]
## Unequal length trials
Right now we require equal length numpy arrays to initialize `AnalogData` objects, something like the following is not possible:
```python
my_data = spy.AnalogData(data=[np.arange(3), np.arange(5)])
```
As there is no real problem with allowing this, and for the sake of inter-operability (np.arrays as a fundamental datatype within the Python eco-system), we should amend the initialization routine to allow for this. 

## Generators
In the spirit of a small memory footprint, it might be good to also allow generator expressions inside this init method:
```python
my_gen = (np.arange(5+ i) for i in range(10))
my_data = spy.AnalogData(data=my_gen)
```
Such that real _lazy evaluation_ of expressions returning `np.arrays` _trial-by-trial_ becomes possible.

**Comment by tensionhead** [comment]
I think it might be easier to manipulate the trialdefinition after the Syncopy data object got initialized with some numpy arrays. Otherwise we would need to submit additional information about the size of the data OR use the hdf5 feature of growing datasets like `shape=(None, nChannels)`. As it's not super urgent I remove it from the last '22 release.

**Comment by dfsp-spirit** [comment]
This is implemented, closing as done.
