### ISSUE TITLE
Refurbish `.copy()`

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#286]
## The Problem
This important functionality does not integrate anymore with our current code base, producing for example this behaviour:
```python
my_copy = my_data.copy()
# manipulate copy
my_copy = 99 * my_copy
# access original data
my_data.show()
>> SPYValueError: Invalid value of `data`: 'backing HDF5 file /home/whir/.spy/spy_7aa7_be564476.analog has been closed'; expected open HDF5 file
```
With `.copy(deep=True)` the above example works just fine.

The **doc-string** is also misleading:
```
Signature: my_data.copy(deep=False)
Docstring:
Create a copy of the data object in memory.
```
As in the above example a mere symlink to the existing data on disc gtets created.

## Proposed Solution
A *non-deep* copy does not makes sense with our hdf5 backend, so just leaving the `deep=True` functionality and removing this parameter should do the trick. For *in-memory* operations, we already have `.show()`, and `.selectdata()`.

**Comment by dfsp-spirit** [comment]
@tensionhead This is done, right? Do you want to close this?

**Comment by tensionhead** [comment]
Yes of course, dont get why linked PRs don't close issues automatically upon merge :/

**Comment by dfsp-spirit** [comment]
I also thought that was the case once...
