### ISSUE TITLE
Extended time-/frequency-selection support

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#29]
We want to support by-trial variations in time-/frequency-selections, i.e., things like

```python
select = {"trials": [5, 1, 4], "toi": [[0, 3, 1], [0, 1, 2], [3]]}
```
FieldTrip supports similar functionality in some cases (e.g., by-trial `toilim`s in `ft_redefinetrial`).

**Comment by tensionhead** [comment]
This seems like a somewhat obscure feature with no current practical use cases, so I am closing this.
