### ISSUE TITLE
Include `block_info` keyword in `computeFunction`s

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#30]
**Is your feature request related to a problem? Please elaborate.**
Currently, it is not possible for parallel workers spawned by `ComputationalRoutine` to determine which trial-(channel-)chunk they're currently processing. This will probably be necessary for some more elaborate `computeFunction`s (that might also require inter-worker communication). 

**Do you have a solution in mind? Please elaborate**
We should incorporate a new mandatory keyword for `computeFunction`s: following dask's `map_blocks` array method, we should consider implementing a `block_info` keyword (following dask's nomenclature): `block_info` will be a dictionary providing references to the current chunk-index and respective trial number. Adhering to dask's naming scheme should make the keyword quite self-explaining to developers familiar with dask arrays.

**Comment by tensionhead** [comment]
Channel parallelization uses `c_blocks` internally to deal with chunks, so this most likely is no longer relevant. Good be a good target for refactoring the CR though.. yet this is not planned atm.
