### ISSUE TITLE
Check frontend for `select` kw documentation

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#300]
Neiter `freqanalysis` nor `preprocessing` are mentioning that handy selection mechanism at all atm

**Comment by pantaray** [comment]
The corresponding docu is dynamically injected by the `unwrap_select` decorator. The idea is that every meta function that uses the decorator obviously supports the `select` keyword and thus could use some mention of this functionality in its docstring ;)

**Comment by tensionhead** [comment]
Ahaa.. true :+1: Ok thx, happily closing this :slightly_smiling_face:
