### ISSUE TITLE
Auxiliary meta info container

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#303]
## Feature request
We want/need a lightweight container structure where users can store auxiliary (meta-)information inside Syncopy containers. 
## Solution idea
Attaching an `.info` attribute to our data classes, saved in the `.json` along with the data and holding for example a `StructDict` (akin to `cfg`) might be an easy way to achieve this. 

Somewhat related to #209

**Comment by dfsp-spirit** [comment]
@tensionhead Can we close this as done, now that we have `.info`?

**Comment by tensionhead** [comment]
Yes of course, again I expected merged linked branches would close this automatically
