### ISSUE TITLE
Feature Flags

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#306]
To avoid release blocks bc of unfinished (untested!) features, we want to think of a way to silence (meta-)functions such that they don't get exposed to the public API. Bonus for Sphinx also not picking those up when auto-building the doc :grin:

**Comment by dfsp-spirit** [comment]
Fowler has an interesting article [here](https://martinfowler.com/articles/feature-toggles.html), it's quite lengthy and more complicated than we need though, but still a good read.

Take home messages:

* _on/off state_: use one convention for what is on/off. Best: **on** means that the **new** code is active.
* place feature toggles early (at the borders of a system): near the user frontend in our case.
* keep them in a config file (or database), not code, so they can be switched at run-time (less important for us, its not a web service or compiled app, but still good design I think). nice is a config file that can be managed with code, for changing it automatically (e.g., during tests with/without the new feature).

**Comment by tensionhead** [comment]
Ok thanks for digging into this @dfsp-spirit! I guess some additional config file is the best solution, depending on the granularity of the switches. Switching on/off specific methods within the same meta-function is probably much more involved than just hiding an unfinished (yet still integrated) user frontend. Let's keep track of this, and see what use cases we really have?!

**Comment by tensionhead** [comment]
As this was not really an issue in recent times, and given current time constraints I am closing for now
