### ISSUE TITLE
Support setting plot title in plots

### ISSUE THREAD

**Issue by dfsp-spirit** [esi-neuroscience/syncopy#313]
**Is your feature request related to a problem? Please elaborate.**
When running scripts or unit tests which produce several plots, it would be great if it was possible to set plot titles, so it is easier to see what a particular plot shows (or is supposed to show).

This applies to functions like `singlepanelplot`.

**Do you have a solution in mind? Please elaborate**
The plotting functions would need more parameters.

**Not really a problem per se, more like a missing feature? Please elaborate**
It would be great to have an API like `my_data_instance.singlepanelplot(title="A great title here")`.

**Additional context**
n/a

**Thank you for taking the time to help us improve Syncopy!**

**Comment by tensionhead** [comment]
Thx for the feature request, this boils down to propagate additional mpl parameters to the plotting backends. Which also for other things (specify fig num for example) would be quite nice. With the current implementation this isn't easily possible, I can try to see how to get this done. 

For now, you can do sth like:
```pytthon
fig, ax = my_data.singlepanelplot()
ax.set_title('My awesome title')
```

This should work?!

**Comment by dfsp-spirit** [comment]
Oh yes, that's good enough I guess. 

Maybe we can close this, the solution show be good enough. We could do it like this in some tutorial/example in the docs, so people get it.

**Comment by dfsp-spirit** [comment]
I am closing this for now, the workaround should be good enough and the priority seems quite low.
