### ISSUE TITLE
Account for "creative" time-selections

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#32]
**Describe the bug**
Currently, it's possible to perform selections a la `toi = [0, 10, 3, 5, 3, 3, 3, 3, 0, 0, 10, 15]` which correctly re-shuffles and appends time-points. However, the resulting object's `time` property is completely (borderline catastrophically) wrong. 

For situations like this, we could introduce a hidden `_time` attribute and extend the `time` property as follows:

```python
    @property
    def time(self):
        """list(float): trigger-relative time axes of each trial """
        if self._time is not None:
            return self._time
        
        if self.samplerate is not None and self.sampleinfo is not None:
            return [(np.arange(0, stop - start) + self._t0[tk]) / self.samplerate \
                    for tk, (start, stop) in enumerate(self.sampleinfo)]

    @time.setter
    def time(timearr):
        # Ensure consistency of input array
        nSamples = self.trials[0].shape[self.dimord.index("time")]
        try:
            array_parser(timearr, varname="time", dimensions=(len(self.trials), nSamples),
                         hasinf=False, hasnan=False)
        except Exception as exc:
            raise exc
        self._time = np.array(timearr)
```

**Note** All trial-getters can stay as they are, since they rely on `sampleinfo` which (at least for trial-getting purposes) basically encodes the by-trial sample counts. 

**Note further** This issue's significance has been promoted w/new time-frequency objects (that may very well originate from things like ``toi = [-0.1,  0.1,  0.3,  0.4])``

**Comment by pantaray** [comment]
Now right now, but I guess at some point we have to. Or remove support for non-equidistant/repeating `toi` selections

**Comment by tensionhead** [comment]
With #378  this is no longer relevant
