### ISSUE TITLE
Independent component analysis (ICA) for the data

### ISSUE THREAD

**Issue by kajal5888** [esi-neuroscience/syncopy#328]
**Is your feature request related to a problem? Please elaborate.**
Independent Component Analysis (ICA) – have been steadily gaining popularity in the last years as viable techniques to preprocess multivariate data sets, to disentangle information linearly mixed by volume conduction in the recorded data channels, and to perform or prepare for more general data mining.

**Comment by dfsp-spirit** [comment]
Development info:

* the MNE function is [mne.preprocessing.ICA](https://mne.tools/stable/generated/mne.preprocessing.ICA.html)
* fieldtrip tutorials on ICA can be found at [example/ica_ecg](https://www.fieldtriptoolbox.org/example/ica_ecg/) and [example/ica_eog](https://www.fieldtriptoolbox.org/example/ica_eog/)

**Comment by dfsp-spirit** [comment]
For now we

**Comment by dfsp-spirit** [comment]
@kajal5888 I guess you intend to get results similar to those in Fieldtrip? Apparently they support 2 different algorithms, one of them can be used with or without PCA. Quoting from their documentation of [runica](https://github.com/fieldtrip/fieldtrip/blob/master/external/eeglab/runica.m):

```
Perform Independent Component Analysis (ICA) decomposition
%            of input data using the logistic infomax ICA algorithm of 
%            Bell & Sejnowski (1995) with the natural gradient feature 
%            of Amari, Cichocki & Yang, or optionally the extended-ICA 
%            algorithm of Lee, Girolami & Sejnowski, with optional PCA 
%            dimension reduction. 
```

Could you let me know what you your call to runica looks like? E.g., the most simple case with the default algorithm would be:

```matlab
[weights,sphere] = runica(data);
```

**Comment by dfsp-spirit** [comment]
Some interesting papers related to ICA and MEG/EEG data:

* https://onlinelibrary.wiley.com/doi/full/10.1111/psyp.12147
* https://ieeexplore.ieee.org/document/7319296?reload=true

**Comment by dfsp-spirit** [comment]
We decided to provide the FastICA method for know, using the implementation from `scikit-learn`. This will add scikit-learn as a dependency of Syncopy, but that is absolutely fine with us, as almost anybody is most likely using that anyways.

**Comment by dfsp-spirit** [comment]
We could have a look at this FT [example dataset](https://download.fieldtriptoolbox.org/tutorial/ArtifactMEG.zip) linked [here](https://www.fieldtriptoolbox.org/faq/what_types_of_datasets_and_their_respective_analyses_are_used_on_fieldtrip/) for the unit tests.

**Comment by dfsp-spirit** [comment]
A great overview of the types of noise to expect can be seen at 5:52 in [this youtube ICA video by the EEGLAB team](https://www.youtube.com/watch?v=pSYqVBp5ZjU&list=PLXc9qfVbMMN2uDadxZ_OEsHjzcRtlLNxc)

**Comment by dfsp-spirit** [comment]
ICA requires a lot more work than just the implementation of an ICA algorithm, e.g., topoplots so users can identify the components they want to filter from their data (heartbeats, eye blinks, etc). Furthermore, MNE has great interactive viewers for these, and our group/users do hardly use ICA, we decided **not to implement ICA in Syncopy** for now.

Instead, we will make it easier to switch back and forth between Syncopy and MNE, as described in issue #491. This will allow users to perform ICA in MNE, then continue in Syncopy.
