### ISSUE TITLE
TimelockData

### ISSUE THREAD

**Issue by joschaschmiedt** [esi-neuroscience/syncopy#33]
For storing the output of `timelockanalysis` we need a subclass of `StatisticalData`. Fieldtrip's `ft_timelockanalysis` outputs the following shapes:
```

avgFIC = 

  struct with fields:

      time: [1×900 double]
     label: {149×1 cell}
      elec: [1×1 struct]
      grad: [1×1 struct]
       avg: [149×900 double]
       var: [149×900 double]
       dof: [149×900 double]
    dimord: 'chan_time'
       cov: [149×149 double]
       cfg: [1×1 struct]

```
the `cov` field is optional. With `cfg.keeptrials = 'yes'` the output looks like this:

```
avgFIC = 

  struct with fields:

          time: [1×900 double]
         label: {149×1 cell}
          elec: [1×1 struct]
          grad: [1×1 struct]
    sampleinfo: [77×2 double]
         trial: [77×149×900 double]
     trialinfo: [77×1 double]
        dimord: 'rpt_chan_time'
           cov: [77×149×149 double]
           cfg: [1×1 struct]
```

**Comment by tensionhead** [comment]
This discussion is still ongoing, for now the projected averaging operator (#230) simply will return the same dataclass (e.g. `SpectralData` --> `SpectralData`) with one contracted (length 1) axis holding the average(s) respectively.

**Comment by tensionhead** [comment]
I think we should at least link this to the upcoming "sequential_statistics" issue/branch @dfsp-spirit ?!

**Comment by tensionhead** [comment]
completed with #381
