### ISSUE TITLE
One-off rounding errors for resampling

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#336]
## The problem

Going into `spy.resampledata` with equal trial length, can produce unequaly trial output lengths.. affected are both down and resampling if the new samplerate is not an integer division of `nSamples` :disappointed: 

Suppose we have 991 samples in an `AnalogData` object `ad`:
```python
ad.sampleinfo[:2]
>>> array([[   0.,  991.],
          [ 991., 1982.]])
# trial length
np.diff(ad.sampleinfo[:2], axis=1)
>>> array([[991.],
           [991.]])

```
And now we update the sampleinfo with `// 2` as in `Downsample.process_metadata`:
```python

ad.sampleinfo[:2] // 2
>>> array([[  0., 495.],
           [495., 991.]])
# trial length
np.diff(ad.sampleinfo[:2] // 2, axis=1)
>>> array([[495],
           [496]])
```
Or update with `np.ceil` as in `Resample.process_metadata`:
```
np.ceil(ad.sampleinfo[:2] / 2)
>>> array([[  0., 496.],
           [496., 991.]])
# trial length
np.diff(np.ceil(ad.sampleinfo[:2] / 2, axis=1))
>>> array([[496],
           [495]])
```
So we get unequal trials no matter what, however even different ones depending on the method.

## Solution
In both cases the actual correct trial length is 496, which we could learn bei `np.ceil`ing the original trial-lengths times the resampling factor (not the `sampleinfo` directly), and then build a trialdefinition from there.

**Comment by dfsp-spirit** [comment]
@tensionhead I guess this can be closed?
