### ISSUE TITLE
Data class specific checkdata method

### ISSUE THREAD

**Issue by joschaschmiedt** [esi-neuroscience/syncopy#34]
Inspired by [`ft_checkdata`](http://www.fieldtriptoolbox.org/reference/ft_checkdata/), it may be useful to have a `checkdata` method for all data classes, which checks whether all necessary properties are filled with sensible values, e.g. whether the `avg`, `var`, `dof` arrays of TimelockData have matching shapes.

**Comment by tensionhead** [comment]
As far as I can tell, we have intrinsic checks during data object instantiation which will complain if something is not right.
