### ISSUE TITLE
Support setting RNG seed in test data generators for reproducible unit tests

### ISSUE THREAD

**Issue by dfsp-spirit** [esi-neuroscience/syncopy#344]
**Is your feature request related to a problem? Please elaborate.**
Sometimes unit tests that are based on random data fail because of 'bad luck' with drawn values. This is especially annoying for devs if it happens during CI runs.

**Do you have a solution in mind? Please elaborate**
Support setting RNG seed in test data generators for reproducible unit tests.

**Additional context**
unit tests

**Thank you for taking the time to help us improve Syncopy!**

**Comment by dfsp-spirit** [comment]
Please list any tests that are affected here, whenever you encounter CI issues:

* snycopy/tests/test_specest_fooof.py/TestFooofSpy.test_different_fooof_outputs_are_consistent()
    - the line that may fail is `assert 27 < out_fooof_peaks.freq[f1_ind] < 33`

**Comment by dfsp-spirit** [comment]
This is now WIP in branch [344_rng](https://github.com/esi-neuroscience/syncopy/tree/344_rng).

**Comment by dfsp-spirit** [comment]
This is ready for review now.

**Comment by tensionhead** [comment]
With #355 mergend this is done :rocket:
