### ISSUE TITLE
Specify/fixate metadata labels

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#345]
## Current status
Thanks to #140 we can now propagate additional returns from our cFs to the frontend results. @dfsp-spirit made a strong argument for putting at least some of those into `.info` to allow programmatic access for users, as opposed to for example simply writing those to `.log`. 

## The issue
Then we should also document these additional 'hooks' properly, meaning that the metadata/info (they don't have to be the same) keys are also programmatically accessible, at least by Sphinx. The easiest I could imagine is to attach them to the derived CRs in question: 
```python
class SomeCR(ComputationalRoutine):
 
    metadata_keys = ('converged', 'rel. tol')
    # this cF guy can access the keys (if needed)
    # as class attributes of this CR
    computeFunction = staticmethod(some_cF)
    
    ...
    def process_metadata(self, data, out):
    
        mdata = metadata_from_hdf5_file(out.filename)
        
        for key in self.metadata_keys:
            # assume here for simplicity that
            # keys directly match
            out.info[key] = mdata[key]    
```
Such that Sphinx can access and render via `:data:~syncopy.module.compRoutines.SomeCR.metadata_keys`.

What do you think @dfsp-spirit ?

**Comment by dfsp-spirit** [comment]
Yes, I absolutely agree that this should show up in the docs somewhere, otherwise its pointless.

I think this is a good solution.

**Comment by dfsp-spirit** [comment]
There is one problem with this approach though: currently the metadata keys in there may be auto-generated based on the `trial_idx` and `call_idx`, e.g., for FOOOF, one gets something like this:

    gaussian_params_0_1
    gaussian_params_0_2
    gaussian_params_0_3
    gaussian_params_0_4
    gaussian_params_1_0
    ...
    peak_params_0_0
    peak_params_0_1
    ...

so there can be quite a lot of them. Of course, this could be solved by grouping them with another dictionary layer, e.g.:

    md = { 'gaussian_params' : { gaussian_params_0_0 : ndarray1,  
                                                  gaussian_params_0_1 : ndarray2,  
                                                 },
               'peak_params' : { peak_params_0_0 : ndarray1,  
                                            peak_params_0_1 : ndarray2,  
                                          }
             }

I will give it a try.

**Comment by dfsp-spirit** [comment]
This is WIP [in PR 356](https://github.com/esi-neuroscience/syncopy/pull/356).

**Comment by tensionhead** [comment]
Let's also put all the additional returned metadata into the `.info` property of our output objects, right in #356

**Comment by tensionhead** [comment]
With the #356 merge, we fixated the `metadata_keys` as class attributes of the respective CR attaching the metadata as planned.
 
Serialization into `.info` is still not entirely solved, right @dfsp-spirit ? However if that is really generally needed, we'll wait for user feedback, so I am closing this.
