### ISSUE TITLE
`DiscreteData` does not support `toilim` selection

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#348]
As can be seen [here](https://github.com/esi-neuroscience/syncopy/blob/3043c86accccc0f8037d6ac0e160117a4d42d182/syncopy/datatype/base_data.py#L1539), `toi/toilim` selections are not supported for `DiscreteData` and `EventData` objects. At the moment I don't really see why, maybe @pantaray has some orignal motivation to share?

**Comment by pantaray** [comment]
I'm not sure why the linked code line prevents `toi/toilim` selections. In theory, both `SpikeData` and `EventData` *should* support `toi`/`toilim` selections - there are even tests for this: https://github.com/esi-neuroscience/syncopy/blob/958b6923a4bd26ebe690fd67a8e42e3806d8480e/syncopy/tests/test_selectdata.py#L667
Granted, outside this test-routine I don't think this functionality has ever been actually used in the wild, so I would expect things to break in colorful ways ;)

**Comment by tensionhead** [comment]
The linked code states:
```
if self._dataClass in ["SpikeData", "EventData"]:
    trlDef = trl[self.trial_ids, :]
```
So this means the new trialdefintion is just the old one with the selected trials, no `toi/toilim` selection gets digested as for the other datatypes below?!

**Comment by tensionhead** [comment]
With `latency` as new keyword in `selectdata` this does is most likely not longer relevant.
