### ISSUE TITLE
GitHub CI Pipeline broken with new poetry version 1.2.1

### ISSUE THREAD

**Issue by dfsp-spirit** [esi-neuroscience/syncopy#353]
The GitHub CI pipeline has stopped working today, with an error message:

    Could not parse version constraint:

See [here](https://github.com/esi-neuroscience/syncopy/actions/runs/3081752935/jobs/4980655454) for an example. Without any changes on the branches (e.g., dev branch), re-running the test CI workflow now fails.

I noticed today (Monday, 2022-09-19), that there has been a new poetry release v1.2.1 on Friday (2022-09-16), see [its changelog here](https://github.com/python-poetry/poetry/blob/master/CHANGELOG.md). Apparently they changed something about semver parsing which breaks with one of the version strings used in our dependencies. The reason is most likely one of several changes in parsing of semver things mentioned in the changelog of the (included and updated) version of [poetry-core v1.2.0](https://github.com/python-poetry/poetry-core/releases/tag/1.2.0), which is part of that new poetry release.

The poetry error message above shows the version string it chokes on as empty, and even with very verbose output (`poetry install -vvv`), poetry does not show the actual package to which this version string belongs in the error message.

**Comment by dfsp-spirit** [comment]
I have, for now, fixed the poetry version [here in PR 352 on dev](https://github.com/esi-neuroscience/syncopy/pull/352).

With this change, we can continue working an have the CI pipeline running for any changes. Still, this is only a short-term solution. We will need to remove the fixed poetry version and fix the broken version string soon, so that our CI also works with the latest poetry release.

**Comment by dfsp-spirit** [comment]
This was fixed in [PR 354](https://github.com/esi-neuroscience/syncopy/pull/354) now, see commit e0a854a6649fecd1d901701fa5047e845c9a30bd. Closing as done.

**Comment by tensionhead** [comment]
Ok great job you solved this so quickly and cleanly :+1: :slightly_smiling_face:
