### ISSUE TITLE
syncopy.CrossSpectralData.singlepanelplot() returns None

### ISSUE THREAD

**Issue by dfsp-spirit** [esi-neuroscience/syncopy#357]
syncopy.CrossSpectralData.singlepanelplot() returns None instead of `(fig, ax)`-tuple, like other datatypes (AnalogData, SpectralData).

This means one cannot set a plot title or axis limits, which is quite inconvenient when plotting many things in a script.

**Comment by dfsp-spirit** [comment]
After inspecting the code, the fig and ax can be accessed after plotting from the data object, as `myCrossSpectralDatainstance.fig` and `myCrossSpectralDatainstance.ax`.

So this may be a non-issue.

**Comment by tensionhead** [comment]
Got addressed in #365
