### ISSUE TITLE
Very very slow loading of Spike data in current dev branch

### ISSUE THREAD

**Issue by KatharineShapcott** [esi-neuroscience/syncopy#360]
**Describe the bug**

Went from 180 ms to 9.43 seconds!

![image](https://user-images.githubusercontent.com/65502584/194599829-544fb0d6-b581-4ee9-b4c6-56d6740df374.png)

This seems to be specific to spike data, here I'm looping through all the data types in a folder and most times are similar: 
```
0.3.dev187
ADC
CPU times: user 7.22 ms, sys: 4.03 ms, total: 11.2 ms
Wall time: 25.6 ms
events
CPU times: user 264 ms, sys: 3.99 ms, total: 268 ms
Wall time: 271 ms
lfp
CPU times: user 2.99 ms, sys: 1.02 ms, total: 4.01 ms
Wall time: 6.57 ms
raw
CPU times: user 4.83 ms, sys: 4 µs, total: 4.84 ms
Wall time: 16.9 ms
spikes
CPU times: user 9.21 s, sys: 214 ms, total: 9.42 s
Wall time: 9.46 s
```

```
2022.8.1a0
ADC
CPU times: user 5.93 ms, sys: 0 ns, total: 5.93 ms
Wall time: 7.25 ms
events
CPU times: user 4.68 ms, sys: 713 µs, total: 5.4 ms
Wall time: 5.39 ms
lfp
CPU times: user 2.35 ms, sys: 1.95 ms, total: 4.3 ms
Wall time: 4.17 ms
raw
CPU times: user 3.35 ms, sys: 2.06 ms, total: 5.41 ms
Wall time: 4.88 ms
spikes
CPU times: user 160 ms, sys: 19.9 ms, total: 180 ms
Wall time: 181 ms
```

Files sizes looks like this:
![image](https://user-images.githubusercontent.com/65502584/194602298-d58c229e-4b65-405a-b345-b464733f4dc8.png)

**To Reproduce**
Switch to the current dev branch and load in spike data.

**Expected behavior**
Loading time stays the same as previously.

**System Profile:**
 - OS: ESI cluster
 - Please paste the output of the following command here 
   ```python
   import syncopy as spy; spy.AnalogData().log
   ```

		>>> SyNCopy v. 0.3.dev187 <<< 

Created: Fri Oct  7 18:29:01 2022 

System Profile: 
3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0] 
ACME:  0.21
Dask:  2021.10.0
NumPy: 1.21.2
SciPy: 1.7.3

--- LOG ---

|=== shapcottk@esi-svhpc23: Fri Oct  7 18:29:02 2022 ===|

	__init__: created AnalogData object

**Additional Information**
I don't notice any change in the memory usage and it's not specific to loading with tags.

**Comment by tensionhead** [comment]
So the problem at hand got solved, however we found unexpected (nTrials^2 + nTrials) scaling of that expensive and with the fix avoided again equality check.. and we are wondering why for a simple init of `AnalogData` the `__eq__` operator gets into action in the first place.
