### ISSUE TITLE
Inter-trial coherence (ITC)

### ISSUE THREAD

**Issue by kajal5888** [esi-neuroscience/syncopy#367]
**Is your feature request related to a problem? Please elaborate.**

Intertrial coherence (ITC) is a measure of how consistent oscillatory phase is across an ensemble of trials.

Please provide a clear and concise description of the problem. If possible/applicable, please consider providing a minimal complete working example illustrating the problem.

https://www.mattcraddock.com/blog/2020/06/12/what-is-intertrial-coherence/

**Not really a problem per se, more like a missing feature? Please elaborate**
Please provide a description of what kind of functionality you want to see in Syncopy. If possible/applicable, please consider writing a few lines of (pseudo-)code to illustrate your thoughts.

This measure is usually the part of the connectivity analysis. I can provide the code but the need to be implemented into the connnectivity analysis

**Thank you for taking the time to help us improve Syncopy!**

**Comment by tensionhead** [comment]
Ok so inspecting this ITC formula closely, this measure is typically called the **Kuramoto order parameter** (https://mathinsight.org/applet/kuramoto_order_parameters) in physics or alternatively **length of the resultant vector** in [directional statistics](https://en.wikipedia.org/wiki/Directional_statistics) given by: 

$R = \frac{1}{N} \left | \sum_i e^{i\theta_i} \right | $

which is mathematically the same as the definition given in your source @kajal5888. Btw their video did not really help imho :grin:  

So this is maybe best understood as an **unweighted coherence** in Neuro-sprech. should be pretty straightforward to implement :)
