### ISSUE TITLE
Implement Welch's method for freqanalysis

### ISSUE THREAD

**Issue by nazgulfg92** [esi-neuroscience/syncopy#368]
**Is your feature request related to a problem? Please elaborate.**
On occasions, one might have long datasets (.i.e hundreds or thousands of seconds) that are not structured into trials. It's not clear how one might deal with the spectral analysis of long time series (e.g. getting just the PSD) in Syncopy, as it appears that it only implements methods that obtain power spectra from the FULL time series. This could lead to noisy spectra that cannot be easily smoothened, e.g. because the automatically calculated number of tapers for certain smoothing (using _tapsmofrq_ ) lies in the thousands.

**Do you have a solution in mind? Please elaborate**
Implement Welch's method (already also in scipy) in Syncopy. Welch's method will chunk the long time series, calculate the spectrum of each chunk, and average them. It's a good solution for long datasets that have no trial structure.

**Comment by tensionhead** [comment]
Thanks for pushing this up the priority chain @nazgulfg92, #135 should have been done a while ago..

**Comment by tensionhead** [comment]
By the way, until we have Welch's Method implemented you could use a windowed Fourier approach:

 ```python
fftconvol_spec =  spy.freqanalysis(data, method='mtmconvol', t_ftimwin=1, toi=0.5)
```
This would calculate individual FFTs along the time axis in 1 second long windows with 50% overlap. Then you could manually average the time axis out, effectively getting a Welch spectral esimate:
```python
# initialize NumPy array to hold the time average
av_spec = np.zeros((1, *fftconvol_spec.data.shape[1:]))
# 1st trial only
for time in fftconvol_spec.time[0]:
    av_spec += fftconvol_spec.show(toi=time, trials=0)
# normalize by number of windows
av_spec /= len(fftconvol_spec.time[0])
# initialize Syncopy SpectralData object with time averaged spectra
welch_spec = spy.SpectralData(data = [av_spec], samplerate=fftconvolve_spec.samplerate)
```
The example above assumes you have only 1 trial. Hope this helps!

**Comment by nazgulfg92** [comment]
Cool! 
It does help, especially for doing from within Syncopy.
I took the liberty anyways to simply use the analog data and plug it into scipy's Welch. Then I'd take that spectrum and use it to initialize a SpectralData in syncopy, to keep using the other cool features.

**Comment by dfsp-spirit** [comment]
Notes for implementation (for Syncopy developers):

* the reference is `Peter D. Welch. The use of fast Fourier transform for the estimation of power spectra: A method based on time averaging over short, modified periodograms. IEEE Transactions on Audio and Electroacoustics, 15(2):70–73, 1967.` [doi:10.1109/TAU.1967.1161901](https://doi.org/10.1109/TAU.1967.1161901).
* Fieldtrip implementation: they don't seem to have a dedicated method, but suggest `'You can also use [ft_redefinetrial](https://www.fieldtriptoolbox.org/reference/ft_redefinetrial) to cut the data into time-windows with some overlap (e.g.. 50%). This basically implements [Welsh’s [sic!] method](https://en.wikipedia.org/wiki/Welch%27s_method) for spectral estimation.'` [here in the docs](https://www.fieldtriptoolbox.org/workshop/madrid2019/tutorial_freq/)
* MNE Implementation: their `Raw`, `Epochs`, and `Evoked` data classes have a `compute_psd` method, which can be called with `method=welch`. See [here for a tutorial that mentions it](https://mne.tools/stable/auto_tutorials/time-freq/10_spectrum_class.html#sphx-glr-auto-tutorials-time-freq-10-spectrum-class-py). The function behind it, with a full parameter list, is [mne.time_frequency.psd_array_welch](https://mne.tools/stable/generated/mne.time_frequency.psd_array_welch.html).

**Comment by tensionhead** [comment]
Added with #383
