### ISSUE TITLE
Exception on calling syncopy.cleanup

### ISSUE THREAD

**Issue by kajal5888** [esi-neuroscience/syncopy#387]
**Describe the bug**

    Syncopy <core> WARNING: Temporary storage folder /cs/home/kajald/.spy contains 484 files taking up a total of 190.00 GB on disk. 
    Consider running `spy.cleanup()` to free up disk space.
    
    Syncopy <cleanup> Analyzing temporary storage folder /cs/home/kajald/.spy...
    
    
    SyNCoPy encountered an error in 
    
    Step7a_DJ_TrialShuffling.py, line 27 in <module>
	    snp.cleanup(interactive=False)
    
    --------------------------------------------------------------------------------
    Abbreviated traceback:
    
    /mnt/hpc/home/kajald/DJ_Software/syncopy/syncopy/io/utils.py, line 122 in cleanup
	    with open(sess, "r") as fid:
    
    Use `import traceback; import sys; traceback.print_tb(sys.last_traceback)` for full error traceback.
    FileNotFoundError: [Errno 2] No such file or directory: '/cs/home/kajald/.spy/session_564a_log.id'
    

**To Reproduce**
When syncopy.cleanup is called in parallel processing from several slurm jobs

**Expected behavior**
No error

**Additional Information**
When syncopy.cleanup is called in parallel processing from several slurm jobs

**Thank you again for your time!**

**Comment by tensionhead** [comment]
Yap, catching `FileNotFoundError`'s within `spy.cleanup` should be enough to address this quickly..

**Comment by dfsp-spirit** [comment]
I just wanted to mention that running several Syncopy scripts in parallel via slurm is **not** the intended use case of the software.

In general, one should prefer to run a single Syncopy script, and let it handle parallelization on its own (which happens via slurm if available).

**Comment by dfsp-spirit** [comment]
This is merged, so I am closing this.
