### ISSUE TITLE
Serializable `cfg` entries

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#392]
As reported by @kajal5888, if a frontend parameter (e.g. `foilim`) is set via a non-serializable datatype (like numpy's `int64`) the standard `spy.save` fails because the `cfg` dictionary can't be dumped in to the accompanying json. Easiest to reproduce is sth like this:
```python
my_data = ...  # some AnalogData
cfg = spy.StructDict()                                                                                                                           
cfg.foilim = [80, np.int64(120)]

spec = spy.freqanalysis(my_data, cfg)

spec.save('test')
```
this fails with
```bash
TypeError: Object of type int64 is not JSON serializable
```

## How to Fix Idea

When updating the `.cfg` property of a Syncopy data object (for replayabilty) inside a frontend, it should be checked that all values are serializable, and if possible casted to appropriate types. So `np.int64` -> `int`, `np.float64` -> float and so on

**Comment by dfsp-spirit** [comment]
@kajal5888 The linked PR will not close this imo, maybe this was a misclick?

**Comment by dfsp-spirit** [comment]
This could actually be relevant in more places than just the foilim, maybe we want more general checks, @tensionhead?

Another question is whether we want to *reject* or *try to automatically convert* numpy datatypes as input in cases when they would go into the cfg.

**Comment by tensionhead** [comment]
Yes, afaik all the numpy arrays we do accept in the frontend are of 'the sequence type', e.i. 1d-arrays. For those calling `.tolist(()` before casting to a serializable data type should be straightforward.

**Comment by tensionhead** [comment]
Got done with #407
