### ISSUE TITLE
Add csd to freqanalysis

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#4]
In Fieldtrip, the 'csd' is computed in the `freqanalysis` function. We should probably do the same.

Fieldtrip's `ft_freqanalysis` supports the computation of both power-spectra and cross-spectral densities with 
```matlab
 cfg.output      =  'powandcsd' % return the power and the cross-spectra
```
which then requires  
```matlab
   cfg.channelcmb  = Mx2 cell-array with selection of channel pairs (default = {'all' 'all'}),
                       see FT_CHANNELCOMBINATION for details
```
(see http://www.fieldtriptoolbox.org/reference/ft_freqanalysis/). 

We should make decision on how we compute the cross-spectral densities necessary for spectral connectivity methods. See also #3

**Comment by tensionhead** [comment]
We now finally settled of moving the cross spectra to connectivity, calling the `mtmfft` backend method from specest with e02970028499df9e84ec15fbe3c8b29545da1848
