### ISSUE TITLE
Check out contiguous channel property for discrete data

### ISSUE THREAD

**Issue by tensionhead** [esi-neuroscience/syncopy#408]
Such that integer `channel` column entries directly index `.channel` name array.

**Comment by KatharineShapcott** [comment]
I think in fieldtrip if a channel doesn't have any spikes the label is still present but the cell arrays for that label (e.g. timestamp) are empty.

![image](https://user-images.githubusercontent.com/65502584/210541779-489a1850-bd6a-4185-add7-8218a18b8dc0.png)

**Comment by KatharineShapcott** [comment]
Units are different because each channel can have a different number of units. I think that's fine the way it is (but I haven't tested it yet...)

**Comment by tensionhead** [comment]
Ok, so dataset initialization now actually takes a bit longer, as the default label computation AND the property setter each need one `np.max` (for the channels) or `np.unique` (for the units). However property access thereafter is now much much faster:
### before
```python
In [2]: %timeit spd.unit
4.03 ms ± 22.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [3]: %timeit spd.channel
5.12 ms ± 18.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
### after
```python
In [2]: %timeit spd.unit
58.1 ns ± 0.744 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [3]: %timeit spd.channel
57.4 ns ± 0.225 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each
```
Now onto the test :pray:

**Comment by tensionhead** [comment]
Ok, after some more deep diving I think I found why the proposed contiguous channel label property might never work:
https://github.com/esi-neuroscience/syncopy/blob/6ef6e5db074129c6a40f129ba152224f3181d251/syncopy/datatype/base_data.py#L2219
In case the `.channel` array is larger than the number of actual channels found via `np.unique` (*"dead channels"*), the mapping will always go wrong. 

Not sure how to go from here @KatharineShapcott, the property lookup speedup is something we can and should merge for sure, but the initial goal seems to be unfeasible imho

**Comment by KatharineShapcott** [comment]
Okay I was afraid of that... If the unique only has to be performed once then that's already a big help. What about adding another property, something like `.channel_idx`  which would be the result of the np.unique? Then we know how the channel labels map onto the indicies?

**Comment by tensionhead** [comment]
Yes I was thinking in the same direction, we could define a helper attribute.. which then should also speed up the selections for `SpikeData`.

**Comment by KatharineShapcott** [comment]
I think I know where the performance issue with selectdata might be coming from -> `_get_unit` and `_get_time` are not optimized at all. I'm not sure but `_preview_trial(self, trialno)`

**Comment by tensionhead** [comment]
Sounds good, I haven't looked into the details of the implementation.. but if possible/applicable try to avoid indexing the whole dataset as hdf5 in a non-contiguous ways! Streaming trial-by-trial into an np.array and then do the index operation should be much much faster, especially once #418 is done.

**Comment by KatharineShapcott** [comment]
I had a go in commit 0c1f98855e4f5eebf8027a249d76acf424082401 it's definitely faster for me.

**Comment by tensionhead** [comment]
Even though we did not integrate the proposed changes as originally planned, we got to the desired functionality and most and foremost the speedup with #415
