### ISSUE TITLE
Complete API is sometimes missing from the sidebar

### ISSUE THREAD

**Issue by KatharineShapcott** [esi-neuroscience/syncopy#414]
**Describe the bug**
In the documentation navigation Complete API is not always visible

**To Reproduce**
Go to the following link and the Complete API is no longer visible in the sidebar:
https://syncopy.readthedocs.io/en/latest/user/user_api.html#

![image](https://user-images.githubusercontent.com/65502584/211601285-7e2e706b-8067-4c8f-b4f7-2d97b1eb8086.png)

**Comment by tensionhead** [comment]
Lol, we actually only took that just back in to repair the references :smile: For me it showed this complete API both for the dev and the master rdt build :man_shrugging: In any case, the `User API` is anyways what we had in mind, as it is sorted into sub-categories.

**Comment by KatharineShapcott** [comment]
Ah okay, so maybe the real bug is that from the User API there are no hyperlinks to the main pages for the functions? 

I expected that seeing this:
![image](https://user-images.githubusercontent.com/65502584/211792605-b51091a3-7f1c-4ebd-9c59-cc0ad785fd42.png)

I could click on preprocessing somewhere and reach the full documentation here: https://syncopy.readthedocs.io/en/latest/api/syncopy.preprocessing.html 

Or at least get some information on the possible inputs for the function?

**Comment by tensionhead** [comment]
So this was the situation around the last 4 weeks, where indeed all(!) internal references where broken. But with #413 this got fixed yesterday, here a screenshot from just now: 
![Screenshot from 2023-01-11 14:15:12](https://user-images.githubusercontent.com/10595420/211815612-9b621dfe-2d2a-44bf-90de-623c3a3c0070.png)

Maybe you have a browser caching issue?
