### ISSUE TITLE
Remove memory-map support

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#42]
**Is your feature request related to a problem? Please elaborate.**
We currently _theoretically_ support object creation using memory-mapped NumPy arrays. This functionality is (a) not working everywhere (`spy.save` may or may not crash w/memory maps) (b) barely tested and (c) results in lots and lots of `if`-`else` constructs (particularly in `ComputationalRoutine` and friends) to account for differences in HDF containers and memory maps. It seems questionable, whether memory-map support is a feature that is worth jumping through so many hoops at this point (also considering the terrible performance of memory maps w/GPFS).   

**Do you have a solution in mind? Please elaborate**
We should remove memory map support from Syncopy entirely. If people _really_ want to use memmaps, we can re-include support in a coordinated and clean manner later. At this point, we're sitting on lots of barely functional/untested legacy code.  

@joschaschmiedt Any objections?

**Comment by pantaray** [comment]
There's a lot of broken code flying around inside the package. This should be removed sooner rather than later.

**Comment by dfsp-spirit** [comment]
This was removed in the PR linked above, the changes are now on _dev_. Closing.
