### ISSUE TITLE
`check_workers_available` causes execution to hang

### ISSUE THREAD

**Issue by KatharineShapcott** [esi-neuroscience/syncopy#438]
My code keeps hanging in `check_workers_available`. I think that's because I very commonly request more workers than I get, in this example I requested 192 workers but only got 127.

```
/cs/departmentN5/conda_envs/oesyncopy_v2/lib/python3.8/site-packages/distributed/node.py:183: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 44533 instead
  warnings.warn(
Syncopy <ACME: slurm_cluster_setup> Requested worker-count 192 exceeds `n_workers_startup`: waiting for 20 workers to come online, then proceed
Syncopy <ACME: slurm_cluster_setup> SLURM workers ready: 127/None 	[elapsed time 00:09 | timeout at 01:00]
Syncopy <ACME: ParallelMap> INFO: This is ACME v. 2022.11
Syncopy <ACME: ParallelMap> INFO: Attaching to global parallel computing client <Client: 'tcp://10.100.32.17:35951' processes=127 threads=254, memory=1.85 TiB>
Syncopy <ACME: slurm_cluster_setup> Cluster dashboard accessible at http://10.100.32.17:44533/status
Creating spikes
Syncopy <ACME: ParallelMap> INFO: Preparing 192 parallel calls of `but_filtering_cF` using 192 workers
Syncopy <ACME: ParallelMap> INFO: Log information available at /cs/slurm/shapcottk/shapcottk_20230210-163728
100% |██████████| 192/192 [01:11<00:00]
Syncopy <ACME: ParallelMap> INFO: SUCCESS! Finished parallel computation. 

```

When I finally give up after some minutes of nothing happening I find the code stuck here:

```
  File "/cs/departmentN5/conda_envs/oesyncopy_v2/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3442, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_2228632/4116348771.py", line 1, in <module>
    prep.create_spikes(spy_filename, raw_data=None, partition='16GBXS',  timeout=60)
  File "/mnt/hpc/departmentN5/code/preprocessing/preprocessing/preprocess_ephys.py", line 343, in create_spikes
    filtered = spy.preprocessing(raw_data, filter_class='but', order = 4, freq=[band_cutoffs[0], band_cutoffs[1]], filter_type='bp', direction = 'twopass',
  File "/cs/departmentN5/conda_envs/oesyncopy_v2/lib/python3.8/site-packages/syncopy/shared/kwarg_decorators.py", line 259, in wrapper_cfg
    return func(data, *posargs, **cfg)
  File "/cs/departmentN5/conda_envs/oesyncopy_v2/lib/python3.8/site-packages/syncopy/shared/kwarg_decorators.py", line 386, in wrapper_select
    res = func(*args, **kwargs)
  File "/cs/departmentN5/conda_envs/oesyncopy_v2/lib/python3.8/site-packages/syncopy/shared/kwarg_decorators.py", line 528, in parallel_client_detector
    results = func(*args, **kwargs)
  File "/cs/departmentN5/conda_envs/oesyncopy_v2/lib/python3.8/site-packages/syncopy/preproc/preprocessing.py", line 367, in preprocessing
    filterMethod.compute(
  File "/cs/departmentN5/conda_envs/oesyncopy_v2/lib/python3.8/site-packages/syncopy/shared/computational_routine.py", line 710, in compute
    self.process_metadata(data, out)
  File "/cs/departmentN5/conda_envs/oesyncopy_v2/lib/python3.8/site-packages/syncopy/preproc/compRoutines.py", line 282, in process_metadata
    propagate_properties(data, out)
  File "/cs/departmentN5/conda_envs/oesyncopy_v2/lib/python3.8/site-packages/syncopy/shared/computational_routine.py", line 1109, in propagate_properties
    in_data.selectdata(inplace=True)
  File "/cs/departmentN5/conda_envs/oesyncopy_v2/lib/python3.8/site-packages/syncopy/shared/kwarg_decorators.py", line 259, in wrapper_cfg
    return func(data, *posargs, **cfg)
  File "/cs/departmentN5/conda_envs/oesyncopy_v2/lib/python3.8/site-packages/syncopy/shared/kwarg_decorators.py", line 484, in parallel_client_detector
    check_workers_available(client.cluster)
  File "/cs/departmentN5/conda_envs/oesyncopy_v2/lib/python3.8/site-packages/syncopy/shared/dask_helpers.py", line 46, in check_workers_available
    sleep(1)
```

I really don't want it to wait until all the workers are available, on our cluster this rarely happens for me! 

Maybe we could add something like this to the while loop?

```
if (sec > 60) and (len(workers) > 1):
            break
```

As a secondary point I'm not sure why it's reaching that check because parallel=True, it seems like it goes through fine initially but then winds up there later in preprocessing?

**Comment by tensionhead** [comment]
Mmh, so within the output you posted there is a mix of ACME (1st block) and Syncopy's own dask interface, not sure exactly where you ran into problems now. For me it looks like for the acme output that you got your 192 workers eventually, there was a "SUCCESS", so where/why did you give up? But yeah, if you really end up in a syncopy waiting loop with acme being available, that would be odd/a bug, as those should be mutually exclusive. Does acme start the computations without all the workers being alive yet?
There's definitely an option for this I did not know about before in Dask: 
https://distributed.dask.org/en/stable/api.html#distributed.Client.wait_for_workers 
So for our own, acme independent, Dask interface that would be something we could/should make use of :+1:

**Comment by KatharineShapcott** [comment]
Yes it strange, and also strange that it worked fine for the first pass! 

In this example I waited for 10 minutes and could see on the dashboard that the workers were doing nothing the entire time so pressed ctrl-c. This has happened to me multiple times but I only just realised that it was always that function causing the stalling.

**Comment by tensionhead** [comment]
So I could easily add a different waiting routine.. however I don't think there will be an automated "one size fits all" solution. For example, if you wait just for 1 worker, then computations will start very fast on average. But then could take ages as only a tiny fraction of the requested workers might be effective at least for the 1st computation. In the end that always depends on the particular cluster and workload in question. 

Concerning the internal logic: with `parallel=None` Syncopy searches for a global dask client (that could have been spawned by acme beforehand), and if one is found waits for all workers to be online. So from my current understanding to end up in your weird situation one could do:
- start the first run with an explicit `parallel=True` and acme being available, bypassing syncopy's own dask interface
- 1st computations finish without all workers online
- start a 2nd run with `parallel=None`, hence running into this very strict waiting routine

To move forward: I think waiting for half the requested workers max. 10 minutes before starting the computation could be a reasonable default or what do you think @kshapcott ?

**Comment by tensionhead** [comment]
Well you can't have the cake and eat it :slightly_smiling_face: So the more workers you want to have initially, the longer you have to wait. For our own interface I cooked up this scaling here:
![wait_workers](https://user-images.githubusercontent.com/10595420/218490452-8ca00067-12a8-424a-a7cc-e2906a886adf.png)

So that means if you request 10 workers, syncopy waits until 5 are available, if you request 100 workers you'll wait till you have at least 25 and so on.

I tried to rewire the logic in the branch of the PR linked above, not calling any internal dask interfaces if acme is around. Could you try and see if that now resolves the issue? Thx!

**Comment by KatharineShapcott** [comment]
Sorry I'm technically on holiday at the moment, I can't check this easily right now. The code looks good, seems like it should definitely work better. 

But thinking about it, won't you always lose time by not starting to run as soon as a single job is available? Dask will keep adding workers to the pool once they are available. What do we gain by waiting here? Even a single job can get something done in 10 minutes as opposed to doing nothing whatsoever.

**Comment by tensionhead** [comment]
Yep true, came to similar conclusions in the meantime.. I guess waiting for 1 worker is probably still a good idea though.

**Comment by tensionhead** [comment]
Done with #440
