### ISSUE TITLE
Retire VirtualData

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#44]
**Is your feature request related to a problem? Please elaborate.**
As it stands right now, the `VirtualData` class is a piece of working but borderline useless code that requires a plethora of workarounds in multiple places throughout the code. It is very questionable, whether our `VirutalData` is ever going to be used "in the wild" so keeping it around seems like a lot of unnecessary work. 

**Do you have a solution in mind? Please elaborate**
We should remove `VirtualData` from the package. If we find ourselves to ever need the same or related functionality, we can still go back and salvage the code.  

@joschaschmiedt Any objections?

**Comment by dfsp-spirit** [comment]
The class has been removed in 07985d8f46fd, closing.
