### ISSUE TITLE
Include tests for multiple positional args in ComputationalRoutine

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#45]
> 
> 
> > @pantaray, I tried to fined tests for a `ComputationalRoutine` with multiple positional arguments. Do they exist? If not should I open an issue?
> 
> Currently, we do not test that. However, multiple positional arguments are a mandatory requirement for all time-frequency methods (which was actually the reason for me to re-visit `in-grid` and `si-grid` in the first place ;) ). So, as soon as TF-stuff is operational, we will automatically test this functionality. However, if you want to have explicit tests for multiple positional args of `ComputationalRoutine`, I'm def. open for it (of course, those tests will be more artificial in nature, but might make debugging easier).

Ideally I think we should have an explicit test for that (for the unlikely case that the TF implementation changes). Let's have an issue for that.

_Originally posted by @joschaschmiedt in https://github.com/esi-neuroscience/syncopy/pull/38#issuecomment-616466711_

Currently, using multiple positional arguments in a `computeFunction` of a `ComputationalRoutine` instance is supported but so far completely untested. While time-frequency analysis methods make use of this functionality and thus testing `mtmconvol` and `wavelet` automatically tests the handling of multiple positional args in a `computeFunction`, we should probably include explicit tests for this (very crucial) functionality in the package for
two reasons: (a) interweaving these tests w/TF tests makes debugging unnecessarily hard and (b) as @joschaschmiedt rightly points out, in the unlikely event the TF implementation changes, the functionality tests silently disappear without notice.

**Comment by tensionhead** [comment]
The support for multiple input data objects got removed with Syncopy 2022.12
