### ISSUE TITLE
Large temporary files get written when running connectivityanalysis on datasets with many trials

### ISSUE THREAD

**Issue by dfsp-spirit** [esi-neuroscience/syncopy#458]
**Describe the bug**
Large temporary files get written when running connectivityanalysis on datasets with many trials.

* DJ's spy temp dir on the cluster contains some temp files in `~/.spy/tmp_storage/` which are ~ 1.3 TB (**!**) in size *per file*. This should not happen in the first place, regardless of whether it gets reported or not.
    * We just identified when it happens (when large files are created), and it is when running `spy.connectivityanalysis` with the `csd` method. The very large files are _.crosspectral_ syncopy files.
    * They result from running connectivity analysis on a medium data set (8GB), but with 180,000 (!) trials.
* Way less important, there exist some directories named `ACME_<date>_<time>_<msecs>` in DJs user home (not in the Syncopy directory), e.g., `ACME_230307_150312_523756`. These directories are small though, so they not much of a concern right now, but we should still find out under which circumstances they are being created and what we can do to clean them up, as they look like temporary data.

**To Reproduce**
```
#!/usr/bin/env python3

import syncopy as spy
import numpy as np
dt = spy.load("~/DataCombined_StimulusCPAll_vertical_Epoched_WindowLength50msSlidWinNr1.spy")   # file from DJ, available on ESI cs
cfg = spy.get_defaults(spy.connectivityanalysis)
res = spy.connectivityanalysis(dt, cfg)
```

**Expected behavior**
No very large tempfiles in the TB range get created.

**Comment by pantaray** [comment]
Hi! Thanks for the thorough investigation! The `ACME_<date>_<time>_<msecs>` folders most likely originate from a (non-Syncopy-related) call of `ParallelMap` with `write_worker_results = True`. However, not being able to identify what created these output directories is not great - I will change ACME's default behavior to always include a log-file in these auto-generated directories unless explicitly disabled by the user.

**Comment by tensionhead** [comment]
From my investigation, there does not seem to be a problem of unnecessary files written to disc. 
One thing one has to keep in mind: with `method='csd'` and `keeptrials=True` the connectivity output will be of size
$$nChannels \times input$$. Meaning that with 1GB input data and 200 channels, you end up with 200GB of data which is **much larger** than the input dataset size. 
Other connectivity methods like coherence ('coh') or `granger` implicitly apply a trial average, the resulting dataset has then a size of $$\frac{nChannels}{nTrials} \times input$$, which is typically **smaller** than the input.

**Comment by tensionhead** [comment]
There was however a problem with saving virtual datasets though, they were NOT deleted in `spy.__storage__`..

**Comment by tensionhead** [comment]
Done with #499
