### ISSUE TITLE
Creating a dummy dataset using snp.AnalogData does not create a data set with desired name of the channels

### ISSUE THREAD

**Issue by kajal5888** [esi-neuroscience/syncopy#478]
Thank you for taking the time to report an issue! We know that writing detailed error reports takes effort, and we appreciate you taking the time.

**Describe the bug**
Creating a dataset using snp.AnalogData with the desired names of the channels does not give the requested output.

**To Reproduce**

DataArray = np.random.random((100,5))
DesiredChannelNames = ['V1Channel1','V1Channel2','V1Channel3','V4hannel1','V4Channel2']
DummyData = snp.AnalogData(data=DataArray, samplerate=25, channel=DesiredChannelNames)
DummyData.channel
array(['channel1', 'channel2', 'channel3', 'channel4', 'channel5'], dtype='<U8')

**Expected behavior**
The name of the channel to be the same and the name give as input

**System Profile:**
 - OS: ESI Cluster

**Comment by tensionhead** [comment]
Yup indeed, thx for reporting! As a quick workaround, just set the `channel` property after data object init:
```python
DummyData = snp.AnalogData(data=DataArray, samplerate=25) 
DummyData.channel=DesiredChannelNames
```

**Comment by kajal5888** [comment]
Thanks! I did that.
