### ISSUE TITLE
Adding a `.pre-commit-config.yaml` file

### ISSUE THREAD

**Issue by Sai-Suraj-27** [esi-neuroscience/syncopy#557]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'm thinking about adding a pre-commit configuration file (`.pre-commit-config.yaml `) to the codebase as it helps improve the code quality and maintain consistency within the project. It will allow all the developers/future contributors to maintain a consistent code style. Adding this will help us by running some automated checks before anyone tries to make a commit. Many Python based organizations/repos maintain a pre-commit configuration file for these benefits. So, if you think it is useful let me know I will make a PR, Thank you.

**Comment by dfsp-spirit** [comment]
Thanks for the idea, but at this time I cannot tell you what should put into such a file.

I think that the Syncopy core developers would first need to discuss internally and decide [i]what exactly to put into[/i] such a file. We already have rules we adhere to. And we would prefer, for example, **not** to have something that enforces that we 'cut every line after 79 chars', to be honest. Still, in general I think the idea of a `.pre-commit-config.yaml` to enforce our rules is not bad. We will think about it.

**Comment by Sai-Suraj-27** [comment]
@dfsp-spirit Sure, sir thanks for the reply. We can start by creating a basic `.pre-commit-config.yaml` that formats all the code according to the code-formatter `black`. Note that it is not mandatory to follow the rule of 'cut every line after 79 chars'. We can simply change the maximum-line-length to 120 or whatever we want. Let me know if you want me to make a PR, Thank you.
