### ISSUE TITLE
cfg.inputfile and cfg.outputfile

### ISSUE THREAD

**Issue by joschaschmiedt** [esi-neuroscience/syncopy#60]
In Fieldtrip, many functions can be called with `cfg.inputfile` and `cfg.outputfile`, which loads the data from the inputfile and writes the result into the output file. We should consider whether we want to support this at the level of the meta-functions (`freqanalysis`, `connectivityanalysis`, ...), potentially in combination with having the function parameters in a (JSON) file.

**Comment by dfsp-spirit** [comment]
This adds complexity (like additional required tests, etc) without that much of an improvement. Unless people request with a good reason, we will not implement it. Closing for now.
