### ISSUE TITLE
Support calling Syncopy meta-functions via parameter files

### ISSUE THREAD

**Issue by joschaschmiedt** [esi-neuroscience/syncopy#61]
In order to support calling Syncopy from MATLAB, a versatile solution could be to support parameter files for meta-functions, e.g JSON files such as 

```json
{
    "function" : "freqanalysis",
    "inputfile" : "path/to/data",
    "outputfile" : "path/to/output",
    "method" : "mtmfft",
    "taper" : "dpss",
    "tapsmofrq" : 10, 
    ...
}
```
Calling it then with `syncopy.py <jsonfile>` is more or less straightforward from any environment. Creating JSON files in MATLAB is also relatively easy (yaml & co. currently are not).

**Comment by tensionhead** [comment]
Calling syncopy from matlab fortunately is no longer planned.
