### ISSUE TITLE
Include in-place preprocessing via decorator

### ISSUE THREAD

**Issue by joschaschmiedt** [esi-neuroscience/syncopy#62]
Similar to our `select` keyword and the `@unwrap_select` decorator, we should support on-demand pre-processing of data (e.g., smoothing) via keyword (`preproc` maybe?), similar to many Fieldtrip functions (`cfg.preproc`). This could be done using an additional `@unwrap_preproc` decorator, for instance.

**Comment by tensionhead** [comment]
Not sure if this is as straightforward as the `select` keyword and decorator, as preprocessig involves actual number-crunching.. so we would have to call the entire frontend (`preprocessing`) via a keyword (`preproc`) and pipe its output to the actual frontend call (say `freqanalysis`)

**Comment by tensionhead** [comment]
We have `spy.preprocessing` as separate frontend which offers a good standard API for things like smoothing, so I am closing this.
