### ISSUE TITLE
Reconsider data type of channel property

### ISSUE THREAD

**Issue by joschaschmiedt** [esi-neuroscience/syncopy#64]
Currently, `BaseData.channel` is a NumPy array, however, whenever we do something involving `channel` we find ourselves converting `channel` to a list, e.g. for plotting. Maybe `channel` should be a list in the first place?

**Comment by tensionhead** [comment]
So more than 2 years in, it seems like `channel` being a numpy array works just fine. It probably still is a good idea, however as there is no direct need and the amount of refactoring required unclear I am closing this.
