### ISSUE TITLE
Extended documentation of freqanalysis

### ISSUE THREAD

**Issue by joschaschmiedt** [esi-neuroscience/syncopy#65]
Currently, `freqanalysis` has only `Parameters` and `Returns` sections. It should also include Examples, Notes and See also sections (one of which should ideally point to a Tutorial).

**Comment by tensionhead** [comment]
I will start working on a freqanalysis tutorial!

**Comment by tensionhead** [comment]
However the function doc itself is already rather voluminous atm, closing this!
