### ISSUE TITLE
Don't accept non-integers for DiscreteData

### ISSUE THREAD

**Issue by joschaschmiedt** [esi-neuroscience/syncopy#67]
Currently it's possible to write floats into `DiscreteData.data`. This should be prevented.

**Comment by tensionhead** [comment]
So far this did no bite us, however we don't have much experience with discrete data yet. @kshapcott you think this is still relevant?

**Comment by KatharineShapcott** [comment]
Actually this did bite us already, someone accidently wrote nans into DiscreteData which turned out weird. Would be nice to prevent this beforehand...
