### ISSUE TITLE
Implement "smart" concatenation in BaseData

### ISSUE THREAD

**Issue by joschaschmiedt** [esi-neuroscience/syncopy#69]
Implement a class method that simplifies the process of "stitching together" two data objects of similar type. For instance, if `ob1` and `obj2` are both `"label" x "sample"` `AnalogData` objects with `(M, N) = ob1.data.shape` and `(M, K) = ob2.data.shape`, then `ob1.stack(ob2)` should yield an object with shape `(M, N + K)` (simultaneously ensuring that samplerates, time-axes etc. don't clash).

The `._filename` attribute of `BaseData` already supports lists "implicitly"

**Comment by pantaray** [comment]
Closed by 2d5fae796cc5828f77586218570db0378a1527c5
