### ISSUE TITLE
filename_parser: return dict-based class 

### ISSUE THREAD

**Issue by joschaschmiedt** [esi-neuroscience/syncopy#70]
Currently the [`filename_parser`](https://github.com/esi-neuroscience/syncopy/blob/master/syncopy/shared/parsers.py#L512) returns a `dict`. We may want to encapsulate the dictionary returned by filename_parser in a separate class that can be easily refactored.

**Comment by tensionhead** [comment]
Closing this as it's probably out of date/the current implementation does its job
