### ISSUE TITLE
Perform data selection in plotting routines via `select`

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#86]
**Is your feature request related to a problem? Please elaborate.**
Currently, all major meta functions in Syncopy support in-place data selections via a `select` keyword. To keep things consistent, we should support this data-selection avenue in the plotting routines as well. 

**Do you have a solution in mind? Please elaborate**
Use `unwrap_select` to permit in-place data-subset selections via a `select` dict.

**Comment by tensionhead** [comment]
Closing this as we already overhauled the plotting, now using `.show` which indeed uses `select` in the background!
