### ISSUE TITLE
Permit data selection in plotting routines using either `select` or `keywords`

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#87]
**Is your feature request related to a problem? Please elaborate.**
cf. #86

**Do you have a solution in mind? Please elaborate**
In addition to permitting data-selection via `select`, allow FieldTrip-style selections using keyword arguments, **but not both**.

**Comment by tensionhead** [comment]
As all current plotting routines support `show_kwargs` which via `.show()` directly support `select` keywords I think this is resolved.
