### ISSUE TITLE
Rename select keywod to pre_select

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#90]
Following the [standup mtg from 28.05.20](https://github.com/orgs/esi-neuroscience/teams/syncopy-dev/discussions/5) , rename the `select` keyword `pre_select` to emphasize precedence of `select` over meta-function 'output' selectors (e.g., first perform an in-place selection of a specific time-interval in the input object, `pre_select={'toilim':[-0.1, 0.2]}` then choose a frequency range in the output `foilim = [30, 70]` in `freqanalysis`)

**Comment by tensionhead** [comment]
Is this still an idea you want to pursue @pantaray ?

**Comment by pantaray** [comment]
Not sure. That's something which is probably best decided by our users. I think we can close this one for now.
