### ISSUE TITLE
Implement a small-scale version of FieldTrip's databrowser

### ISSUE THREAD

**Issue by pantaray** [esi-neuroscience/syncopy#92]
Since we want to support both notebook and desktop workflows, a backend-agnostic solution would be great, e.g.
```python
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Button
 
freqs = np.arange(2, 20, 3)
 
fig, ax = plt.subplots()
plt.subplots_adjust(bottom=0.2)
t = np.arange(0.0, 1.0, 0.001)
s = np.sin(2*np.pi*freqs[0]*t)
l, = plt.plot(t, s, lw=2)
 
 
class Index(object):
    ind = 0
 
    def next(self, event):
        self.ind += 1
        i = self.ind % len(freqs)
        ydata = np.sin(2*np.pi*freqs[i]*t)
        l.set_ydata(ydata)
        plt.draw()
 
    def prev(self, event):
        self.ind -= 1
        i = self.ind % len(freqs)
        ydata = np.sin(2*np.pi*freqs[i]*t)
        l.set_ydata(ydata)
        plt.draw()
 
callback = Index()
axprev = plt.axes([0.7, 0.05, 0.1, 0.075])
axnext = plt.axes([0.81, 0.05, 0.1, 0.075])
bnext = Button(axnext, 'Next')
bnext.on_clicked(callback.next)
bprev = Button(axprev, 'Previous')
bprev.on_clicked(callback.prev)
 
plt.show()
```
I suspect that for massive multi-channel data browsing there's no way around a backend-specific solution.

_Originally posted by @joschaschmiedt in https://github.com/esi-neuroscience/syncopy/issues/21#issuecomment-600654525_

> Looking at the respective performance requirements, it seems practicable to build both `ft_singleplot` as well as `ft_multiplot` upon `matplotlib`.
> 
> However, `ft_databrowser` might call for a faster visualization framework. After experimenting with and researching various tools (including `matplotlib`'s `animation` package and some `blit` pixel magic), it seems to me that [pyqtgraph](http://www.pyqtgraph.org/) might be our best option here. It is lightning fast, easy to install (`conda install pyqtgraph`), requires "only" `pyqt` and is specifically tailored to realtime scientific data visualizations. It seems very mature (first release in 2013) and was written by some of the `VisPy` authors, who say "_[VisPy] is presently in early development and has a narrower scope than PyQtGraph--it will focus on visualization without the GUI toolkit features provided by PyQtGraph._" Since we specifically _want_ a GUI toolkit, `pyqtgraph` seems like the more straight forward choice for us.
> 
> To get an idea what `pyqtgraph` code looks like, here an example stolen from https://stackoverflow.com/a/40139416
> 
> ```python
> import sys
> import time
> from pyqtgraph.Qt import QtCore, QtGui
> import numpy as np
> import pyqtgraph as pg
> 
> 
> class App(QtGui.QMainWindow):
>     def __init__(self, parent=None):
>         super(App, self).__init__(parent)
> 
>         #### Create Gui Elements ###########
>         self.mainbox = QtGui.QWidget()
>         self.setCentralWidget(self.mainbox)
>         self.mainbox.setLayout(QtGui.QVBoxLayout())
> 
>         self.canvas = pg.GraphicsLayoutWidget()
>         self.mainbox.layout().addWidget(self.canvas)
> 
>         self.label = QtGui.QLabel()
>         self.mainbox.layout().addWidget(self.label)
> 
>         self.view = self.canvas.addViewBox()
>         self.view.setAspectLocked(True)
>         self.view.setRange(QtCore.QRectF(0,0, 100, 100))
> 
>         #  image plot
>         self.img = pg.ImageItem(border='w')
>         self.view.addItem(self.img)
> 
>         self.canvas.nextRow()
>         #  line plot
>         self.otherplot = self.canvas.addPlot()
>         self.h2 = self.otherplot.plot(pen='y')
> 
> 
>         #### Set Data  #####################
> 
>         self.x = np.linspace(0,50., num=100)
>         self.X,self.Y = np.meshgrid(self.x,self.x)
> 
>         self.counter = 0
>         self.fps = 0.
>         self.lastupdate = time.time()
> 
>         #### Start  #####################
>         self._update()
> 
>     def _update(self):
> 
>         self.data = np.sin(self.X/3.+self.counter/9.)*np.cos(self.Y/3.+self.counter/9.)
>         self.ydata = np.sin(self.x/3.+ self.counter/9.)
> 
>         self.img.setImage(self.data)
>         self.h2.setData(self.ydata)
> 
>         now = time.time()
>         dt = (now-self.lastupdate)
>         if dt <= 0:
>             dt = 0.000000000001
>         fps2 = 1.0 / dt
>         self.lastupdate = now
>         self.fps = self.fps * 0.9 + fps2 * 0.1
>         tx = 'Mean Frame Rate:  {fps:.3f} FPS'.format(fps=self.fps )
>         self.label.setText(tx)
>         QtCore.QTimer.singleShot(1, self._update)
>         self.counter += 1
> 
> 
> if __name__ == '__main__':
> 
>     app = QtGui.QApplication(sys.argv)
>     thisapp = App()
>     thisapp.show()
>     sys.exit(app.exec_())
> ```

**Comment by dfsp-spirit** [comment]
This seems quite a bit of work to implement and support, we need to talk with Pascal whether we want to do this.

**Comment by dfsp-spirit** [comment]
I don't see this being added soon, closing.
